{% set name = "django-auth-ldap" %}
{% set version = "2.2.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/{{ version }}.tar.gz
  sha256: b8ca4fa54982f84522f4fe2505d2df23f9a410c70f44a7ffa6663ac66cf40ec0

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - django
    - pip
    - python-ldap
    - python
  run:
    - django
    - python-ldap
    - python

about:
  home: https://github.com/django-auth-ldap/django-auth-ldap
  license: BSD
  license_family: BSD
  license_file:
  summary: Django LDAP authentication backend
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
    - Coop56
