{% set name = "django-auth-ldap" %}
{% set version = "4.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 269c6a8e962303e2fd70f1035c133d9118bca75799f08d2567a803ea3086c830

build:
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - django {% if django is defined %} {{ django }} {% endif %}
    - pip
    - python-ldap >=3.1
    - python {% if python is defined %} {{ python }} {% endif %}
  run:
    - django {% if django is defined %} {{ django }} {% endif %}
    - python-ldap >=3.1
    - python {% if python is defined %} {{ python }} {% endif %}

about:
  home: https://github.com/django-auth-ldap/django-auth-ldap
  license: BSD
  license_family: BSD
  license_file:
  summary: Django LDAP authentication backend
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
    - Coop56
