{% set name = "django-storages" %}
{% set version = "1.12.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/jschneier/django-storages/archive/refs/tags/{{version}}.tar.gz
  sha256: d461d6208e31df80cec99637f58faa867f3fc88c0826eac4efabb64aac6bf086

build:
  script: "{{ PYTHON }} -m pip install . --no-deps -vv "

requirements:
  host:
    - pip
    - python {% if python is defined %} {{ python }} {% endif %}
  run:
    - python {% if python is defined %} {{ python }} {% endif %}
    - django {% if django is defined %} {{ django }} {% endif %}

about:
  home: https://github.com/jschneier/django-storages
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'django-storages is a project to provide a variety of storage backends in a single library.'
  description:
    This repo began as a fork of the original library under the package name of django-storages-redux
    and became the official successor (releasing under django-storages on PyPI) in February of 2016.
    This library is usually compatible with the currently supported versions of Django.
    Check the Trove classifiers in setup.py to be sure.
  doc_url: https://django-storages.readthedocs.io/en/latest/
  dev_url: https://github.com/jschneier/django-storages
