# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-24 18:31
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import oet2.jobs.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionMask',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('the_geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Mask for export regions')),
            ],
            options={
                'db_table': 'region_mask',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExportConfig',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(db_index=True, default='', max_length=255)),
                ('config_type', models.CharField(choices=[('PRESET', 'Preset'), ('TRANSLATION', 'Translation'), ('TRANSFORM', 'Transform')], default='PRESET', max_length=11)),
                ('filename', models.CharField(max_length=255)),
                ('upload', models.FileField(max_length=255, upload_to=oet2.jobs.models.get_upload_path)),
                ('content_type', models.CharField(editable=False, max_length=30)),
                ('published', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'export_configurations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ExportProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('max_extent', models.IntegerField()),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='export_profile', to='auth.Group')),
            ],
            options={
                'db_table': 'export_profiles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ExportProvider',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Service Name')),
                ('slug', oet2.jobs.models.LowerCaseCharField(max_length=10, unique=True, default='')),
                ('url', oet2.jobs.models.LowerCaseCharField(blank=True, default='', max_length=1000, null=True, verbose_name='Service URL')),
                ('layer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Service Layer')),
                ('type', oet2.jobs.models.LowerCaseCharField(choices=[('osm', 'OpenStreetMap'), ('wms', 'WMS'), ('wfs', 'WFS'), ('wmts', 'WMTS'), ('dg', 'Digital Globe')], default='wms', max_length=3, verbose_name='Service Type')),
            ],
            options={
                'db_table': 'export_provider',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, default='', max_length=100)),
                ('key', models.CharField(db_index=True, default='', max_length=50)),
                ('value', models.CharField(db_index=True, default='', max_length=50)),
                ('data_model', models.CharField(db_index=True, default='', max_length=10)),
                ('geom_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=10), default=[], size=None)),
                ('groups', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=100), default=[], size=None)),
            ],
            options={
                'db_table': 'tags',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='exporttask',
            name='job',
        ),
        migrations.RemoveField(
            model_name='job',
            name='status',
        ),
        migrations.AddField(
            model_name='job',
            name='event',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='feature_pub',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='feature_save',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='published',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.Region'),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.CharField(db_index=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ExportTask',
        ),
        migrations.AddField(
            model_name='tag',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='jobs.Job'),
        ),
        migrations.AddField(
            model_name='job',
            name='configs',
            field=models.ManyToManyField(blank=True, related_name='configs', to='jobs.ExportConfig'),
        ),
    ]
