# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-24 18:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', 'create_hstore_extension'),
        ('jobs', 'install_default_group'),
        ('jobs', 'insert_export_formats'),
        ('jobs', 'load_regions'),
        ('jobs', 'create_tag_gin_index'),
    ]

    operations = [
    ]
