# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-15 12:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', 'insert_export_formats'),
        ('jobs', 'insert_export_providers'),
        ('jobs', 'load_regions'),
        ('jobs', 'create_tag_gin_index'),
    ]

    operations = [
    ]
