# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-25 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportProviderType',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('type_name', models.CharField(default='', max_length=4, unique=True, verbose_name='Type Name')),
                ('supported_formats', models.ManyToManyField(blank=True, to='jobs.ExportFormat', verbose_name='Supported Export Formats')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProviderTask',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('formats', models.ManyToManyField(related_name='formats', to='jobs.ExportFormat')),
            ],
        ),
        migrations.RemoveField(
            model_name='exportprovider',
            name='type',
        ),
        migrations.RemoveField(
            model_name='job',
            name='formats',
        ),
        migrations.AddField(
            model_name='providertask',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider', to='jobs.ExportProvider'),
        ),
        migrations.AddField(
            model_name='exportprovider',
            name='export_provider_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.ExportProviderType', verbose_name='Service Type'),
        ),
        migrations.AddField(
            model_name='job',
            name='provider_tasks',
            field=models.ManyToManyField(related_name='provider_tasks', to='jobs.ProviderTask'),
        ),
    ]
