# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-10 15:47
from __future__ import unicode_literals

from django.db import migrations
import oet2.jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_exportprovider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportprovider',
            name='url',
            field=oet2.jobs.models.LowerCaseCharField(default='', max_length=1000, unique=True),
        ),
    ]
