# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-06 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import oet2.jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20160810_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportprovider',
            name='layer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Service Layer'),
        ),
        migrations.AddField(
            model_name='exportprovider',
            name='type',
            field=oet2.jobs.models.LowerCaseCharField(choices=[('osm', 'OpenStreetMap'), ('wms', 'WMS'), ('wfs', 'WFS'), ('wmts', 'WMTS'), ('dg', 'Digital Globe')], default='wms', max_length=3, verbose_name='Service Type'),
        ),
        migrations.AlterField(
            model_name='exportprovider',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Service Name'),
        ),
        migrations.AlterField(
            model_name='exportprovider',
            name='url',
            field=oet2.jobs.models.LowerCaseCharField(blank=True, default='', max_length=1000, null=True, verbose_name='Service URL'),
        ),
    ]
