package:
  name: libkml
  version: 1.3.0

source:
  fn: 1.3.0.tar.gz
  url: https://github.com/libkml/libkml/archive/1.3.0.tar.gz

build:
  number: 0

about:
  home: https://github.com/libkml

# vim:set ts=8 sw=2 sts=2 tw=78 et: