# Generated by Django 2.2.5 on 2020-04-10 15:34

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', 'add_map_image_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=100, null=True)),
                ('comment', models.TextField(blank=True, default='', null=True, verbose_name='Comment')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataProviderRequest',
            fields=[
                ('userrequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user_requests.UserRequest')),
                ('name', models.CharField(max_length=100, verbose_name='Service Name')),
                ('url', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Service URL')),
                ('service_description', models.TextField(blank=True, default='', null=True, verbose_name='Description')),
                ('layer_names', models.TextField(blank=True, default='', null=True, verbose_name='Layer Names')),
            ],
            options={
                'abstract': False,
            },
            bases=('user_requests.userrequest',),
        ),
        migrations.CreateModel(
            name='SizeIncreaseRequest',
            fields=[
                ('userrequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user_requests.UserRequest')),
                ('the_geom', django.contrib.gis.db.models.fields.MultiPolygonField(default='', srid=4326, verbose_name='Extent for export')),
                ('requested_aoi_size', models.IntegerField(blank=True, null=True, verbose_name='Requested AOI Size')),
                ('requested_data_size', models.IntegerField(blank=True, null=True, verbose_name='Requested Data Size')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_provider', to='jobs.DataProvider')),
            ],
            options={
                'abstract': False,
            },
            bases=('user_requests.userrequest',),
        ),
    ]
