# Generated by Django 3.2.7 on 2021-10-14 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_requests", "add_size_rules"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersizerule",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
