# Generated by Django 3.2.7 on 2022-03-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_requests', '0001_alter_usersizerule_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersizerule',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='usersizerule',
            constraint=models.UniqueConstraint(fields=('provider', 'user'), name='unique_user_size_rule_per_provider'),
        ),
    ]
