# Generated by Django 2.2.5 on 2020-04-13 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', 'add_map_image_snapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_requests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMaxDataSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_data_size', models.DecimalField(decimal_places=3, default=100, help_text='This is the maximum data size in MB that can be exported from this provider in a single DataPack.', max_digits=12, verbose_name='Max data size')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.DataProvider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('provider', 'user')},
            },
        ),
        migrations.CreateModel(
            name='UserAoiSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_selection_size', models.DecimalField(decimal_places=3, default=100, help_text='This is the maximum area in square kilometers that can be exported from this provider in a single DataPack. This rule is generally superseded by data size.', max_digits=12, verbose_name='Max data size')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.DataProvider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('provider', 'user')},
            },
        ),
    ]
