{% set name = "django-celery-beat" %}
{% set version = "1.4.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bfc22dad2884524697e1fcdfa63c0555a65151a97902c3045cd2cf7bf63970e4

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - celery >=4.0,<5.0
    - django-timezone-field >=2.0
    - pip
    - python
    - python-crontab >=2.3.4
    - setuptools
  run:
    - celery >=4.0,<5.0
    - django-timezone-field >=2.0
    - python
    - python-crontab >=2.3.4
    - setuptools

test:
  imports:
    - django_celery_beat
    - django_celery_beat.migrations
  requires:
    - case >=1.3.1
    - django
    - pytest >=3.0
    - pytest-django
    - pytz >dev

about:
  home: https://github.com/celery/django-celery-beat
  license: BSD
  license_family: BSD
  license_file: 
  summary: Database-backed Periodic Tasks.
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
