{% set name = "django-celery-beat" %}
{% set version = "2.2.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://files.pythonhosted.org/packages/6b/c5/96827d3fc2d73ff542515abd1b39cab06c156e09092466532c7bf68a07f8/{{name}}-{{version}}.tar.gz
  sha256: fdf1255eecfbeb770c6521fe3e69989dfc6373cd5a7f0fe62038d37f80f47e48

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - celery
    - django-timezone-field
    - pip
    - python
    - python-crontab
  run:
    - celery
    - django-timezone-field
    - python
    - python-crontab

test:
  imports:
    - django_celery_beat
    - django_celery_beat.migrations
  requires:
    - case
    - django
    - pytest
    - pytest-django
    - pytz

about:
  home: https://github.com/celery/django-celery-beat
  license: BSD
  license_family: BSD
  license_file:
  summary: Database-backed Periodic Tasks.
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
    - your-github-id-here
