stages:
  - pending
  - lint
  - test
  - results

variables:
  MOUNT_POINT: $CI_PROJECT_DIR
  BRANCH: "master"
  NEXUS_BASE_URL: $NEXUS_BASE_URL
  NEXUS_REPO: "EventKit_eventkit"
  BASE_URL: "http://cloud.eventkit.test:6080"
  SITE_NAME: "cloud.eventkit.test"
  SITE_IP: "127.0.0.1"
  SECRET_KEY: "TESTING"
  VERSION: "1.13.0"

image:
  name: $DOCKER_IMAGE

.default:
  when: always

.front:
  image: "${CI_REGISTRY_PATH}eventkit/eventkit-webpack:${VERSION}"

.back:
  image:
    name: "${CI_REGISTRY_PATH}eventkit/eventkit-base:${VERSION}"
    entrypoint: [ "" ]
  before_script:
    - conda activate eventkit-cloud

.lint:
  stage: lint
  extends: .default

eslint:
  extends:
    - .front
    - .lint
  script:
    - npm run eslint

black:
  extends:
    - .back
    - .lint
  script:
    - black --config /var/lib/eventkit/config/pyproject.toml --check eventkit_cloud

flake8:
  extends:
    - .back
    - .lint
  script:
    - flake8 --config /var/lib/eventkit/config/setup.cfg eventkit_cloud

migrations:
  extends:
    - .back
    - .lint
  script:
    - python manage.py makemigrations eventkit_cloud | grep -i "No changes detected"


.test:
  stage: test
  extends: .default
  
unit-back:
  extends:
    - .back
    - .test
  variables:
    COVERAGE: "True"
    COVERAGE_THRESHOLD: 68
  script:
    - python manage.py test -v=2 --noinput eventkit_cloud

unit-front:
  extends:
    - .front
    - .test
  script:
    - webpack npm run coverage

# TODO: Add back after debugging connection issues in pipeline.
#integration-tests:
#  when: always
#  stage: test
#  tags:
#    - dind
#  script:
#    - python scripts/ci_utils.py
#    - docker-compose up -d --scale celery=3 && docker-compose stop flower map mkdocs || echo $?
#    - mkdir -p exports_stage exports_download && chmod 777 exports_stage exports_download && chown -R 8800:880 . || echo $?
#    - docker-compose exec -T eventkit "echo 'UID ${UID}'" || echo $?
#    - docker-compose exec -T eventkit bash -c 'source activate eventkit-cloud && python manage.py migrate'
#    - docker-compose exec -T eventkit bash -c 'source activate eventkit-cloud && python manage.py loaddata admin_user osm_provider datamodel_presets' || echo $?
#    - docker-compose exec -T eventkit bash -c 'source activate eventkit-cloud && python manage.py run_integration_tests'

pending-tests:
  when: always
  stage: pending
  script:
    - python scripts/github.py pending "Waiting for tests."

pass-tests:
  when: on_success
  stage: results
  script:
    - python scripts/github.py success "All tests pass."

fail-tests:
  when: on_failure
  stage: results
  script:
    - python scripts/github.py failure "The pipeline failed."
