{% set name = "django-notifications-hq" %}
{% set version = "1.6.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://files.pythonhosted.org/packages/12/b9/dd3525a3af44dea70a67f614056750daf4f506a32b1c8af41a2dd335b244/{{ name }}-{{ version }}.tar.gz
  sha256: debeb71b7076b08487b40bf07664d1cc43b9977c4480bbc969b30236dda7a461

build:
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - django {{ django }}
    - django-model-utils
    - jsonfield
    - pip
    - python {{ python }}
    - pytz {{ pytz }}
  run:
    - django {{ django }}
    - django-model-utils
    - jsonfield
    - python {{ python }}
    - pytz {{ pytz }}
    - swapper {{ swapper }}

test:
  imports:
    - notifications
    - notifications.migrations
    - notifications.templatetags

about:
  home: http://github.com/django-notifications/django-notifications
  license: BSD
  license_family: BSD
  license_file:
  summary: GitHub notifications alike app for Django.
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
    - Coop56
