{% set name = "django-notifications-hq" %}
{% set version = "1.7.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/django-notifications/django-notifications/archive/refs/tags/{{version}}.tar.gz
  sha256: 035e0aa15e307b1a49a4b66f94afe94077ada6e9a88265d10c545d283c7d02d7

build:
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - django {% if django is defined %} {{ django }} {% endif %}
    - django-model-utils
    - jsonfield
    - pip
    - python {% if python is defined %} {{ python }} {% endif %}
    - pytz {% if pytz is defined %} {{ pytz }} {% endif %}
  run:
    - django {% if django is defined %} {{ django }} {% endif %}
    - django-model-utils
    - jsonfield
    - python {% if python is defined %} {{ python }} {% endif %}
    - pytz {% if pytz is defined %} {{ pytz }} {% endif %}
    - swapper {% if swapper is defined %} {{ swapper }} {% endif %}

test:
  imports:
    - notifications
    - notifications.migrations
    - notifications.templatetags

about:
  home: http://github.com/django-notifications/django-notifications
  license: BSD
  license_family: BSD
  license_file:
  summary: GitHub notifications alike app for Django.
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
    - Coop56
