{% set name = "swapper" %}
{% set version = "1.3.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 48a814f67be1abefe6c1495013808d1ff8e6b294f78384c88f5a93b81f7015fd

build:
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python {% if python is defined %} {{ python }} {% endif %}
    - setuptools_scm
  run:
    - python  {% if python is defined %} {{ python }} {% endif %}

test:
  imports:
    - swapper
  requires:
    - django

about:
  home: "https://github.com/wq/django-swappable-models"
  license: MIT
  license_family: MIT
  license_file:
  summary: "The unofficial Django swappable models API."
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
    - Coop56
