{% set name = "swapper" %}
{% set version = "1.1.2.post1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 51651018fb027354dd27ff38d5eb47a225d3e642c99b04cff878ae65b1872f64

build:
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python {{ python }}
    - setuptools_scm
  run:
    - python  {{ python }}

test:
  imports:
    - swapper
  requires:
    - django

about:
  home: "https://github.com/wq/django-swappable-models"
  license: MIT
  license_family: MIT
  license_file:
  summary: "The unofficial Django swappable models API."
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
    - Coop56
