{% set name = "mapproxy" %}
{% set version = "1.13.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/{{ version }}.tar.gz
  sha256: a2a7c5764ebf952108fe1afa03c4b14d71608fdfb7cc88e80a0a401c48f1c27c

build:
  entry_points:
    - mapproxy-seed = mapproxy.seed.script:main
    - mapproxy-util = mapproxy.script.util:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {% if python is defined %} {{ python }} {% endif %}
  run:
    - pillow {% if pillow is defined %} {{ pillow }} {% endif %}
    - python {% if python is defined %} {{ python }} {% endif %}
    - pyyaml {% if pyyaml is defined %} {{ pyyaml }} {% endif %}
    - proj {% if proj is defined %} {{ proj }} {% endif %}
    - pyproj {% if pyproj is defined %} {{ pyproj }} {% endif %}
    - gdal {% if gdal is defined %} {{ gdal }} {% endif %}
    - geos {% if geos is defined %} {{ geos }} {% endif %}
    - shapely {% if shapely is defined %} {{ shapely }} {% endif %}

test:
  imports:
    - mapproxy
    - mapproxy.cache
    - mapproxy.client
    - mapproxy.compat
    - mapproxy.config
    - mapproxy.config_template
    - mapproxy.image
    - mapproxy.image.fonts
    - mapproxy.request
    - mapproxy.request.wms
    - mapproxy.script
    - mapproxy.script.conf
    - mapproxy.seed
    - mapproxy.service
    - mapproxy.source
    - mapproxy.util
    - mapproxy.util.ext
    - mapproxy.util.ext.dictspec
    - mapproxy.util.ext.dictspec.test
    - mapproxy.util.ext.tempita
    - mapproxy.util.ext.wmsparse
    - mapproxy.util.ext.wmsparse.test
  commands:
    - mapproxy-seed --help

about:
  home: https://mapproxy.org
  license: Apache Software
  license_family: APACHE
  license_file:
  summary: An accelerating proxy for tile and web map services
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
    - Coop56
