{% set name = "mapproxy" %}
{% set version = "1.13.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 2433f9a05b863cecebe54460c92032cb8d176e0b773b7e08f623db41eb2710a6

build:
  number: 0
  entry_points:
    - mapproxy-seed = mapproxy.seed.script:main
    - mapproxy-util = mapproxy.script.util:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip=21.1
    - python=3.9
  run:
    - pillow
    - python=3.9
    - pyyaml
    - proj=7.1.1
    - gdal=3.1.4
    - geos
    - shapely

test:
  imports:
    - mapproxy
    - mapproxy.cache
    - mapproxy.client
    - mapproxy.compat
    - mapproxy.config
    - mapproxy.config_template
    - mapproxy.image
    - mapproxy.image.fonts
    - mapproxy.request
    - mapproxy.request.wms
    - mapproxy.script
    - mapproxy.script.conf
    - mapproxy.seed
    - mapproxy.service
    - mapproxy.source
    - mapproxy.util
    - mapproxy.util.ext
    - mapproxy.util.ext.dictspec
    - mapproxy.util.ext.dictspec.test
    - mapproxy.util.ext.tempita
    - mapproxy.util.ext.wmsparse
    - mapproxy.util.ext.wmsparse.test
  commands:
    - mapproxy-seed --help

about:
  home: https://mapproxy.org
  license: Apache Software
  license_family: APACHE
  license_file:
  summary: An accelerating proxy for tile and web map services
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
    - Coop56
