package:
  name: libspatialite
  version: 4.3.0a

source:
  fn: libspatialite-4.3.0a.tar.gz
  url: http://www.gaia-gis.it/gaia-sins/libspatialite-4.3.0a.tar.gz

build:
  number: 0

requirements:
  build:
    - sqlite ==3.24.0
    - geos ==3.6.1-0
    - proj ==4.9.3-0
    - freexl ==1.0.2-0
    - zlib ==1.2.11
    - libxml2 ==2.9.8
  run:
    - sqlite ==3.24.0
    - freexl ==1.0.2-0
    - zlib ==1.2.11
    - geos ==3.6.1-0
    - proj ==4.9.3-0
    - libxml2 ==2.9.8
about:
  home: https://www.gaia-gis.it/fossil/libspatialite/index
  license: MPL tri-license

# vim:set ts=8 sw=2 sts=2 tw=78 et:
