# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-19 15:33


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportprovidertask',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
