# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-07-24 15:52


from django.db import migrations
from django.db import models
from uuid import uuid4

class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0029_move_records'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalizerunhooktaskrecord',
            name='cancel_user',
        ),
        migrations.RemoveField(
            model_name='finalizerunhooktaskrecord',
            name='result',
        ),
        migrations.RemoveField(
            model_name='finalizerunhooktaskrecord',
            name='run',
        ),
        migrations.DeleteModel(
            name='FinalizeRunHookTaskRecord',
        ),
        migrations.RemoveField(
            model_name='exportrun',
            name='downloadable',
        ),
        migrations.RemoveField(
            model_name='exporttaskrecord',
            name='estimated_finish',
        ),
        migrations.RemoveField(
            model_name='exporttaskrecord',
            name='progress',
        ),
    ]
