package:
  name: spatialite
  version: 4.3.0

source:
  fn: spatialite-tools-4.3.0.tar.gz
  url: http://www.gaia-gis.it/gaia-sins/spatialite-tools-4.3.0.tar.gz

build:
  number: 0

requirements:
  build:
    - automake
    - geos ==3.6.1-0
    - proj ==4.9.3-0
    - libspatialite ==4.3.0a-0
    - freexl ==1.0.2-0
    - libxml2 ==2.9.8
    - readosm ==1.0.0e-0
    - sqlite ==3.24.0
  run:
    - freexl ==1.0.2-0
    - geos ==3.6.1-0
    - proj ==4.9.3-0
    - libspatialite ==4.3.0a-0
    - readosm ==1.0.0e-0
    - sqlite ==3.24.0
about:
  home: https://www.gaia-gis.it/fossil/spatialite-tools/index
  license: GPLv3

# vim:set ts=8 sw=2 sts=2 tw=78 et:
