package:
  name: osmctools
  version: 0.9.0

source:
  fn: osmctools-0.9.tar.gz
  url: https://gitlab.com/osm-c-tools/osmctools/-/archive/0.9/osmctools-0.9.tar.gz

build:
  number: 0

about:
  home: https://gitlab.com/osm-c-tools/osmctools

requirements:
  build: 
    - {{ compiler('c') }}
    - automake

