package:
  name: osmctools
  version: 0.9.0

source:
  fn: osmctools-0.9.tar.gz
  url: https://gitlab.com/osm-c-tools/osmctools/-/archive/0.9/osmctools-0.9.tar.gz

about:
  home: https://gitlab.com/osm-c-tools/osmctools

test:
  commands:
    - osmupdate --help
    - osmconvert --help
    - osmfilter --help

requirements:
  build: 
    - {{ compiler('c') }}
    - automake
    - autoconf
  host:
    - zlib {{ zlib }}
  run:
    - wget {{ wget }}
    - zlib {{ zlib }}
