{% set version = "2.20.1" %}

package:
  name: requests
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/requests/requests-{{ version }}.tar.gz
  sha256: ea881206e59f41dbd0bd445437d792e43906703fff75ca8ff43ccdb11f33f263

build:
  number: 1000
  script: "python -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - chardet >=3.0.2,<3.1.0
    - idna >=2.5,<2.8
    - urllib3 >=1.21.1,<1.24
    - certifi >=2017.4.17

test:
  imports:
    - requests

about:
  home: http://python-requests.org
  license: Apache 2.0
  license_file: LICENSE
  summary: 'Python HTTP for Humans'

extra:
  recipe-maintainers:
    - jakirkham
    - kalefranz
    - mcg1969
    - mingwandroid
    - msarahan
    - pelson
    - sigmavirus24
    - ocefpaf
    - carlodri
