# Generated by Django 2.2.5 on 2020-08-03 10:37

import uuid

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import eventkit_cloud.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_dataprovider_label'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20181213_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouppermission',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_permissions', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='grouppermission',
            name='permission',
            field=models.CharField(choices=[('MEMBER', 'Member'), ('ADMIN', 'Admin')], max_length=10),
        ),
        migrations.AlterField(
            model_name='jobpermission',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='jobs.Job'),
        ),
        migrations.AlterField(
            model_name='jobpermission',
            name='object_id',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='jobpermission',
            name='permission',
            field=models.CharField(choices=[('READ', 'Read'), ('ADMIN', 'Admin')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='grouppermission',
            unique_together={('user', 'group', 'permission')},
        ),
        migrations.AlterUniqueTogether(
            name='jobpermission',
            unique_together={('job', 'content_type', 'object_id', 'permission')},
        ),
        migrations.AlterModelTable(
            name='jobpermission',
            table='jobpermission',
        ),
        migrations.CreateModel(
            name='AttributeClass',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', eventkit_cloud.core.models.LowerCaseCharField(db_index=True, max_length=40, unique=True)),
                ('filter', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='This field should be a dict which is passed directly to the user model for filtering users. For help see django docs on filtering models.', null=True)),
                ('exclude', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='This field should be a dict which is passed directly to the user model for excluding users. For help see django docs on excluding models.', null=True)),
                ('complex', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='This is a thruple of nested thruples represented as lists. Example: \'["blue","==","color"]\'.', null=True, unique=True)),
                ('users', models.ManyToManyField(related_name='attribute_classes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attribute Class',
                'verbose_name_plural': 'Attribute Classes',
                'unique_together': {('filter', 'exclude')},
            },
        ),
    ]
