# Generated by Django 2.2.5 on 2020-08-03 10:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0003_auto_20200803_1037'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='JobPermission',
                ),
            ],
            database_operations=[],
        )
    ]
