# Generated by Django 2.2.5 on 2020-05-20 18:04

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone
import eventkit_cloud.core.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20200519_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeClass',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', eventkit_cloud.core.models.LowerCaseCharField(db_index=True, max_length=40, unique=True)),
                ('filter', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='This field should be a dict which is passed directly to the user model for filtering users. For help see django docs on filtering models.', null=True)),
                ('exclude', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='This field should be a dict which is passed directly to the user model for excluding users. For help see django docs on excluding models.', null=True)),
                ('complex', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='This is a thruple of nested thruples represented as lists. \n                        Example: \'["blue","==","color"]\'.', null=True, unique=True)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attribute Class',
                'verbose_name_plural': 'Attribute Classes',
                'unique_together': {('filter', 'exclude')},
            },
        ),
        migrations.DeleteModel(
            name='JobPermission',
        ),
    ]
