# Generated by Django 2.2.5 on 2020-06-03 20:15

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200520_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributeclass',
            name='complex',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='This is a thruple of nested thruples represented as lists. Example: \'["blue","==","color"]\'.', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='attributeclass',
            name='users',
            field=models.ManyToManyField(related_name='attribute_classes', to=settings.AUTH_USER_MODEL),
        ),
    ]
