# Generated by Django 2.2.5 on 2020-07-16 16:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
        ('core', '0004_auto_20200604_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouppermission',
            name='permission',
            field=models.CharField(choices=[('MEMBER', 'Member'), ('ADMIN', 'Admin')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='grouppermission',
            unique_together={('user', 'group', 'permission')},
        ),
    ]
