{% set name = "django-timezone-field" %}
{% set version = "4.1.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/mfogel/django-timezone-field/archive/refs/tags/{{ version }}.tar.gz
  sha256: c618945413e48776dd35a5bfbe476c7dfb3a5523e0d92769bc111f0d02a6d6d1

build:
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - django {% if django is defined %} {{ django }} {% endif %}
    - pip {% if pip is defined %} {{ pip }} {% endif %}
    - poetry {% if poetry is defined %} {{ poetry }} {% endif %}
    - python {% if python is defined %} {{ python }} {% endif %}
    - pytz {% if pytz is defined %} {{ pytz }} {% endif %}
  run:
    - django {% if django is defined %} {{ django }} {% endif %}
    - python {% if python is defined %} {{ python }} {% endif %}
    - pytz {% if pytz is defined %} {{ pytz }} {% endif %}

test:
  imports:
    - timezone_field

about:
  home: http://github.com/mfogel/django-timezone-field/
  license: BSD
  license_family: BSD
  license_file:
  summary: A Django app providing database and form fields for pytz timezone objects.
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
    - your-github-id-here
