{% set name = "django-timezone-field" %}
{% set version = "4.1.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://files.pythonhosted.org/packages/3d/ce/ba24bb9b0b33243a829836a3f18ce030e5d0738965faf01fb84942688c80/{{ name }}-{{ version }}.tar.gz
  sha256: cffac62452d060e365938aa9c9f7b72d70d8b26b9c60243bce227b35abd1b9df

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - django
    - pip
    - python
    - pytz
  run:
    - django
    - python
    - pytz

test:
  imports:
    - timezone_field

about:
  home: http://github.com/mfogel/django-timezone-field/
  license: BSD
  license_family: BSD
  license_file:
  summary: A Django app providing database and form fields for pytz timezone objects.
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
    - your-github-id-here
