{% set name = "django-timezone-field" %}
{% set version = "4.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://files.pythonhosted.org/packages/c9/33/dc63f43177d1489006a58d95ac46fdf2f15f63f5da2ff1f72917c9c3b090/{{ name }}-{{ version }}.tar.gz
  sha256: 7e3620fe2211c2d372fad54db8f86ff884098d018d56fda4dca5e64929e05ffc

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - django
    - pip
    - python
    - pytz
  run:
    - django
    - python
    - pytz

test:
  imports:
    - timezone_field

about:
  home: http://github.com/mfogel/django-timezone-field/
  license: BSD
  license_family: BSD
  license_file:
  summary: A Django app providing database and form fields for pytz timezone objects.
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
    - your-github-id-here
