{% set name = "django-audit-logging" %}
{% set version = "0.3.0" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "02f8fdd926bba3c6cb3c830658adcc6ffeca5a51987831593836c722660818a2" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://github.com/eventkit/{{ name }}/archive/v{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value|lower }}'
  patches: version.patch

build:
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {% if python is defined %} {{ python }} {% endif %}
    - pip
    - django {% if django is defined %} {{ django }} {% endif %}
  run:
    - python {% if python is defined %} {{ python }} {% endif %}
    - django {% if django is defined %} {{ django }} {% endif %}

test:
  imports:
    - audit_logging

about:
  home: https://github.com/eventkit/django-audit-logging
  license: GPLV2
  license_family: GPL
  license_file: ''
  summary: 'Django-Audit-Logging'
  description: "This tool is adds logging support to a django application."
  doc_url: 'https://github.com/eventkit/django-audit-logging/blob/master/README.md'
  dev_url: 'https://github.com/eventkit/django-audit-logging'

extra:
  recipe-maintainers:
    - jsvrcek
