{% set name = "django-audit-logging" %}
{% set version = "0.2.4" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "c5c08669f57dcb18b121de1b3fe97fd01cb7c33c8f6a7112d87e5715c86694da" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://github.com/eventkit/{{ name }}/archive/v{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value|lower }}'

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - django
  run:
    - python
    - django

test:
  imports:
    - audit_logging

about:
  home: https://github.com/eventkit/django-audit-logging
  license: GPLV2
  license_family: GPL
  license_file: ''
  summary: 'Django-Audit-Logging'
  description: "This tool is adds logging support to a django application."
  doc_url: 'https://github.com/eventkit/django-audit-logging/blob/master/README.md'
  dev_url: 'https://github.com/eventkit/django-audit-logging'

extra:
  recipe-maintainers:
    - jsvrcek
