{% set name = "ogdi" %}
{% set version = "3.2.0" %}

package:
  name: "{{ name }}"
  version: "{{ version }}"

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://sourceforge.net/projects/{{ name }}/files/{{ name }}/{{ version }}/{{ name }}-{{ version }}.tar.gz/download
  sha256: 02a2a535870d460f876ddd4495be2ab881a8c50cf36c868f21224f40db20fa48

build:
  number: 0

about:
  home: http://ogdi.sourceforge.net/

requirements:
  build: 
    - {{ compiler('c') }}
    - automake
    - autoconf
  host:
    - expat
    - proj
    - zlib
  run:
    - expat
    - proj
    - zlib
