package:
  name: proj
  version: 4.9.3

source:
  fn: proj-4.9.3.tar.gz
  url: http://download.osgeo.org/proj/proj-4.9.3.tar.gz

build:
  number: 0

about:
  home: http://trac.osgeo.org/proj/
  license: MIT

# vim:set ts=8 sw=2 sts=2 tw=78 et:
