FROM node:8.12.0-slim

RUN apt-get update && apt-get install -y \
    ruby \
    git \
    libcairo2-dev \
    libjpeg62-turbo-dev \
    libpango1.0-dev \
    libgif-dev \
    build-essential \
    g++

WORKDIR /var/lib/eventkit

COPY ./package.json /var/lib/eventkit/

RUN npm install --quiet

RUN gem install coveralls-lcov

COPY ./eventkit_cloud /var/lib/eventkit/eventkit_cloud
COPY ./config/ui/ /var/lib/eventkit/

CMD ["npm", "start"]
