PATHS_FROM_ECLIPSE_TO_PYTHON = []

DEV_MACHINE_CODE_PATH = os.environ.get('DEV_MACHINE_CODE_PATH')
CONTAINER_CODE_PATH = os.environ.get('CONTAINER_CODE_PATH')
if DEV_MACHINE_CODE_PATH is not None and CONTAINER_CODE_PATH is not None:
    PATHS_FROM_ECLIPSE_TO_PYTHON.append((DEV_MACHINE_CODE_PATH, CONTAINER_CODE_PATH))
