_libgcc_mutex:
- '0.1'
_openmp_mutex:
- '4.5'
_sysroot_linux_64_curr_repodata_hack:
- '3'
amqp:
- 5.1.1
asgiref:
- 3.5.2
attrs:
- 22.1.0
backports:
- '1.0'
backports_functools_lru_cache:
- 1.6.4
beautifulsoup4:
- 4.11.1
billiard:
- 3.6.4.0
blosc:
- 1.21.1
boost_cpp:
- 1.74.0
boto3:
- 1.21.46
botocore:
- 1.24.46
brotlipy:
- 0.7.0
bzip2:
- 1.0.8
c_ares:
- 1.18.1
ca_certificates:
- 2022.6.15
cairo:
- 1.16.0
celery:
- 5.2.6
certifi:
- 2022.6.15
cffi:
- 1.15.1
cfitsio:
- 4.1.0
charset_normalizer:
- 2.0.12
click:
- 8.1.3
click_didyoumean:
- 0.3.0
click_plugins:
- 1.1.1
click_repl:
- 0.2.0
cryptography:
- 37.0.4
curl:
- 7.83.1
cyrus_sasl:
- 2.1.27
dj_database_url:
- 0.5.0
django:
- 4.0.4
django_audit_logging:
- 0.3.1
django_auth_ldap:
- 4.0.0
django_celery_beat:
- 2.2.1
django_extensions:
- 3.1.5
django_filter:
- '21.1'
django_model_utils:
- 4.0.0
django_notifications_hq:
- 1.7.0
django_storages:
- 1.12.3
django_timezone_field:
- 4.1.2
djangorestframework:
- 3.13.1
djangorestframework_gis:
- '0.18'
eventkit_cloud:
- 1.14.0
expat:
- 2.4.8
font_ttf_dejavu_sans_mono:
- '2.37'
font_ttf_inconsolata:
- '3.000'
font_ttf_source_code_pro:
- '2.038'
font_ttf_ubuntu:
- '0.83'
fontconfig:
- 2.14.0
fonts_conda_ecosystem:
- '1'
fonts_conda_forge:
- '1'
freetype:
- 2.12.1
freexl:
- 1.0.6
gdal:
- 3.4.2
gdalutils:
- 1.0.2
gdbm:
- '1.18'
geos:
- 3.10.2
geotiff:
- 1.7.1
gettext:
- 0.19.8.1
gevent:
- 21.12.0
giflib:
- 5.2.1
gmp:
- 6.2.1
greenlet:
- 1.1.3
gunicorn:
- 20.1.0
hdf4:
- 4.2.15
hdf5:
- 1.12.1
icu:
- '69.1'
idna:
- '2.10'
importlib_metadata:
- 4.11.4
importlib_resources:
- 5.9.0
jbig:
- '2.1'
jmespath:
- 1.0.1
jpeg:
- 9e
json_c:
- '0.16'
jsonfield:
- 3.1.0
jsonschema:
- 4.4.0
kealib:
- 1.4.15
kernel_headers_linux_64:
- 3.10.0
keyutils:
- 1.6.1
kombu:
- 5.2.4
krb5:
- 1.19.3
lcms2:
- '2.12'
ld_impl_linux_64:
- 2.36.1
lerc:
- 4.0.0
libblas:
- 3.9.0
libcblas:
- 3.9.0
libcurl:
- 7.83.1
libdap4:
- 3.20.6
libdeflate:
- '1.13'
libdrm_cos7_x86_64:
- 2.4.97
libedit:
- 3.1.20191231
libev:
- '4.33'
libevent:
- 2.1.10
libffi:
- 3.4.2
libgcc_ng:
- 12.1.0
libgdal:
- 3.4.2
libgfortran5:
- 12.1.0
libgfortran_ng:
- 12.1.0
libglib:
- 2.72.1
libglvnd_cos7_x86_64:
- 1.0.1
libglvnd_glx_cos7_x86_64:
- 1.0.1
libgomp:
- 12.1.0
libiconv:
- '1.16'
libidn2:
- 2.3.3
libkml:
- 1.3.0
liblapack:
- 3.9.0
libmagic:
- '5.39'
libnetcdf:
- 4.8.1
libnghttp2:
- 1.47.0
libnsl:
- 2.0.0
libntlm:
- '1.4'
libopenblas:
- 0.3.21
libpng:
- 1.6.37
libpq:
- '14.2'
librttopo:
- 1.1.0
libspatialite:
- 5.0.1
libssh2:
- 1.10.0
libstdcxx_ng:
- 12.1.0
libtiff:
- 4.4.0
libunistring:
- 0.9.10
libuuid:
- 2.32.1
libuv:
- 1.44.2
libwebp:
- 1.2.4
libwebp_base:
- 1.2.4
libxcb:
- '1.13'
libxml2:
- 2.9.12
libzip:
- 1.9.2
libzlib:
- 1.2.12
lz4_c:
- 1.9.3
mapproxy:
- 1.13.2
memcached:
- 1.6.9
mesa_libgl_cos7_x86_64:
- 18.3.4
mesa_libglapi_cos7_x86_64:
- 18.3.4
ncurses:
- '6.3'
nspr:
- '4.32'
nss:
- '3.78'
numpy:
- 1.22.3
openjpeg:
- 2.4.0
openldap:
- 2.4.59
openssl:
- 1.1.1q
osmctools:
- 0.9.0
pcre:
- '8.45'
pillow:
- 9.1.0
pip:
- 22.0.4
pixman:
- 0.40.0
poppler:
- 22.04.0
poppler_data:
- 0.4.11
postgresql:
- '14.2'
proj:
- 9.0.0
prompt_toolkit:
- 3.0.30
psycopg2:
- 2.9.3
pthread_stubs:
- '0.4'
pyasn1:
- 0.4.8
pyasn1_modules:
- 0.2.7
pycparser:
- '2.20'
pyjwt:
- 2.3.0
pymemcache:
- 3.5.2
pyopenssl:
- 20.0.0
pyparsing:
- 3.0.8
pyproj:
- 3.3.1
pyrsistent:
- 0.18.1
pysocks:
- 1.7.1
python:
- 3.10.5
python_abi:
- '3.10'
python_crontab:
- 2.6.0
python_dateutil:
- 2.8.2
python_ldap:
- 3.4.0
python_magic:
- 0.4.25
python_memcached:
- '1.59'
pytz:
- '2022.1'
pyyaml:
- '6.0'
readline:
- 8.1.2
requests:
- 2.27.1
requests_pkcs12:
- '1.10'
ruby:
- 3.1.2
s3transfer:
- 0.5.2
setuptools:
- 63.2.0
shapely:
- 1.8.0
six:
- 1.16.0
snappy:
- 1.1.9
soupsieve:
- 2.3.2.post1
sqlite:
- 3.39.1
sqlparse:
- 0.4.2
swapper:
- 1.3.0
sysroot_linux_64:
- '2.17'
tiledb:
- 2.8.3
tk:
- 8.6.12
typing_extensions:
- 4.3.0
tzcode:
- 2022c
tzdata:
- 2020d
uritemplate:
- 4.1.1
urllib3:
- 1.25.11
vine:
- 5.0.0
waitress:
- 2.1.2
wcwidth:
- 0.2.5
webob:
- 1.8.7
webtest:
- 3.0.0
wget:
- 1.20.3
wheel:
- 0.36.1
whitenoise:
- 5.3.0
xerces_c:
- 3.2.3
xorg_kbproto:
- 1.0.7
xorg_libice:
- 1.0.10
xorg_libsm:
- 1.2.3
xorg_libx11:
- 1.7.2
xorg_libxau:
- 1.0.9
xorg_libxdmcp:
- 1.1.3
xorg_libxext:
- 1.3.4
xorg_libxrender:
- 0.9.10
xorg_renderproto:
- 0.11.1
xorg_xextproto:
- 7.3.0
xorg_xproto:
- 7.0.31
xz:
- 5.2.5
yaml:
- 0.2.5
zipp:
- 3.8.1
zlib:
- 1.2.12
zope_event:
- 4.5.0
zope_interface:
- 5.4.0
zstd:
- 1.5.2
