
package:
  name: "file-geodatabase-api"
  version: "1.5.2"

source:
  - url: https://github.com/Esri/file-geodatabase-api/raw/master/FileGDB_API_1.5.2/FileGDB_API_RHEL7_64.tar.gz
    sha256: 21ec8e88fe25941a6ca335f08ad78433add7b2663e18eadb43bcf4a966288bd7
# - url: https://github.com/Esri/file-geodatabase-api/raw/master/FileGDB_API_1.5.2/FileGDB_API-RHEL7-64gcc83.tar.gz
#   sha256: e83ec3bac93df51255912bd7565abbff0d8a044e35eee763b9a080e71f6057f6

build:
  number: 0
  detect_binary_files_with_prefix: True

about:

  home: https://github.com/Esri/file-geodatabase-api
  license: Apache
  license_file: license/userestrictions.txt
  summary: |
    FileGeodatabaseAPI The File Geodatabase C++ API for Windows, MacOS and Linux. The API provides basic tools that allow the creation of file geodatbases, feature classes and tables. Simple features can be created and loaded. See the README included in each of the zip/tar files for a more complete list. .NET bindings are included.