# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-24 11:46


from django.db import migrations

import eventkit_cloud.jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20161020_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportprovider',
            name='slug',
            field=eventkit_cloud.jobs.models.LowerCaseCharField(default='', max_length=40, unique=True),
        ),
    ]
