# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-07 00:47


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_auto_20170522_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportprovider',
            name='display',
            field=models.BooleanField(default=False),
        ),
    ]
