# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-13 20:39


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0023_auto_20171122_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.Region'),
        ),
    ]
