package:
  name: postgis
  version: 2.2.5

source:
  fn: postgis-2.2.5.tar.gz
  url: http://download.osgeo.org/postgis/source/postgis-2.2.5.tar.gz

build:
  number: 0

requirements:
  build:
    - gdal ==2.2.2-0
    - geos ==3.6.1-0
    - proj ==4.9.3-0
    - json-c ==0.11
    - libxml2
    - postgresql ==9.5.10
  run:
    - gdal ==2.2.2-0
    - geos ==3.6.1-0
    - proj ==4.9.3-0
    - json-c ==0.11
    - libxml2 ==2.9.8
    - postgresql ==9.5.10
about:
  home: http://postgis.net
  license: GPL2

# vim:set ts=8 sw=2 sts=2 tw=78 et:
