package:
  name: freexl
  version: 1.0.2

source:
  fn: freexl-1.0.2.tar.gz
  url: http://www.gaia-gis.it/gaia-sins/freexl-sources/freexl-1.0.2.tar.gz

build:
  number: 0

about:
  home: http://www.gaia-gis.it/gaia-sins/freexl-sources

# vim:set ts=8 sw=2 sts=2 tw=78 et: