package:
  name: libgdal
  version: 2.2.2

source:
  fn: gdal-2.2.2.tar.gz
  url: http://download.osgeo.org/gdal/2.2.2/gdal-2.2.2.tar.gz
  md5: b81b7b31d8984435db1b1637cee80e30


build:
  number: 0

requirements:
  build:
    - curl
#    - expat
    - freexl ==1.0.2
    - geos ==3.6.1-0
    - json-c ==0.11-0
#    - jbig
#    - jpeg
    - libkml ==1.3.0
    - libpng ==1.6.35
    - libpq ==9.6.3-0
    - libspatialite ==4.3.0a-0
#    - libtiff
    - openjpeg ==2.1-0
    - postgresql ==9.5.10
    - proj ==4.9.3-0
    - spatialite ==4.3.0-0
    - sqlite ==3.24.0
#    - zlib  # [not win]
#    - xz
  run:
    - curl
#    - expat
    - freexl ==1.0.2
    - geos ==3.6.1-0
    - json-c ==0.11-0
#    - jbig
#    - jpeg
    - libkml ==1.3.0
    - libpng ==1.6.35
    - libpq ==9.6.3-0
    - libspatialite ==4.3.0a-0
#    - libtiff
    - openjpeg ==2.1-0
    - postgresql ==9.5.10
    - proj ==4.9.3-0
    - spatialite ==4.3.0-0
    - sqlite ==3.24.0
#    - zlib  # [not win]
#    - xz
about:
  home: http://www.gdal.org/
  license: MIT
  summary: 'GDAL: Geospatial Data Abstraction Library'