
package:
  name: "mrsid_dsdk"
  version: "9.5.4"

source:
  - url: https://bin.extensis.com/download/developer/MrSID_DSDK-9.5.4.4709-rhel6.x86-64.gcc531.tar.gz
    sha256: ea3866aaaf518426a3a423072540f89a337d6a423feaa8e6cc9ac16906273b84

build:
  number: 0
  detect_binary_files_with_prefix: True

about:

  home: https://www.extensis.com/support/developers
  license: Commercial
  license_file: LICENSE.pdf
  summary: |
    Extensis offers a range of MrSID Software Kits (SDKs) and development tools for integrating decode (viewing) capabilities and encoding technologies. Decode SDKs for MrSID are provided free of charge for development. This allows developers to integrate viewing of MrSID into their applications. For SDK support questions, please contact Extensis Technical Support.
    The MrSID 9.5 SDK, with support for MrSID Generation 4 files (MG4), is now available. With this SDK you can view and decode MG4 files containing both raster LiDAR data, in addition to MrSID Generation 3, MrSID Generation 2 and JPEG 2000 files. This version adds performance improvements so your images render even faster.
