package:
  name: memcached
  version: 1.6.6

source:
  fn: memcached-1.6.6.tar.gz
  url: https://memcached.org/files/memcached-1.6.6.tar.gz

build:
  number: 0

requirements:
  build:
    - libevent

about:
  home: https://memcached.org/about
