package:
  name: memcached
  version: 1.6.9

source:
  fn: memcached-1.6.9.tar.gz
  url: https://memcached.org/files/memcached-1.6.9.tar.gz
  sha256: d5a62ce377314dbffdb37c4467e7763e3abae376a16171e613cbe69956f092d1

build:
  number: 0

requirements:
  build:
    - libevent
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - libevent

about:
  home: https://memcached.org/about
