package:
  name: memcached
  version: 1.6.9

source:
  fn: memcached-1.6.9.tar.gz
  url: https://memcached.org/files/memcached-1.6.9.tar.gz

build:
  number: 0

requirements:
  build:
    - libevent {% if libevent is defined %} {{ libevent }} {% endif %}
    - openssl {% if openssl is defined %} {{ openssl }} {% endif %}
    - billiard {% if billiard is defined %} {{ billiard }} {% endif %}
  run:
    - libevent {% if libevent is defined %} {{ libevent }} {% endif %}
    - openssl {% if openssl is defined %} {{ openssl }} {% endif %}
about:
  home: https://memcached.org/about
