package:
  name: openldap
  version: 2.4.45

source:
  fn: openldap-2.4.45.tgz
  url: ftp://ftp.openldap.org/pub/OpenLDAP/openldap-release/openldap-2.4.45.tgz

requirements:
  build:
    - berkeleydb ==6.0.19
    - cyrus-sasl ==2.1.26
  run:
    - berkeleydb ==6.0.19
    - cyrus-sasl ==2.1.26

build:
  number: 0

about:
  home: http://www.openldap.org/

# vim:set ts=8 sw=2 sts=2 tw=78 et: