# Generated by Django 2.0.9 on 2018-12-13 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import eventkit_cloud.jobs.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataProviderTaskRecord',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('finished_at', models.DateTimeField(editable=False, null=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('slug', eventkit_cloud.jobs.models.LowerCaseCharField(default='', max_length=40)),
                ('status', models.CharField(blank=True, db_index=True, max_length=20)),
                ('display', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
                'managed': True,
                'db_table': 'data_provider_task_records',
            },
        ),
        migrations.CreateModel(
            name='ExportRun',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('finished_at', models.DateTimeField(editable=False, null=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('worker', models.CharField(default='', editable=False, max_length=50, null=True)),
                ('status', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('expiration', models.DateTimeField(default=django.utils.timezone.now)),
                ('notified', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('delete_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='jobs.Job')),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'managed': True,
                'verbose_name': 'ExportRun (DataPack)',
                'verbose_name_plural': 'ExportRuns (DataPacks)',
                'db_table': 'export_runs',
            },
        ),
        migrations.CreateModel(
            name='ExportTaskException',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('exception', models.TextField(editable=False)),
            ],
            options={
                'managed': True,
                'db_table': 'export_task_exceptions',
            },
        ),
        migrations.CreateModel(
            name='ExportTaskRecord',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('finished_at', models.DateTimeField(editable=False, null=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('celery_uid', models.UUIDField(null=True)),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(blank=True, db_index=True, max_length=20)),
                ('pid', models.IntegerField(blank=True, default=-1)),
                ('worker', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('display', models.BooleanField(default=False)),
                ('cancel_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('export_provider_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.DataProviderTaskRecord')),
            ],
            options={
                'ordering': ['created_at'],
                'managed': True,
                'db_table': 'export_task_records',
            },
        ),
        migrations.CreateModel(
            name='FileProducingTaskResult',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('filename', models.CharField(blank=True, editable=False, max_length=508)),
                ('size', models.FloatField(editable=False, null=True)),
                ('download_url', models.URLField(max_length=508, verbose_name='URL to export task result output.')),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'managed': True,
                'db_table': 'export_task_results',
            },
        ),
        migrations.CreateModel(
            name='UserDownload',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('downloaded_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Time of Download')),
                ('downloadable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='tasks.FileProducingTaskResult')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-downloaded_at'],
            },
        ),
        migrations.AddField(
            model_name='exporttaskrecord',
            name='result',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='export_task', to='tasks.FileProducingTaskResult'),
        ),
        migrations.AddField(
            model_name='exporttaskexception',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='tasks.ExportTaskRecord'),
        ),
        migrations.AddField(
            model_name='dataprovidertaskrecord',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_tasks', to='tasks.ExportRun'),
        ),
    ]
