# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-15 12:04


import uuid

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportProviderTask',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'export_provider_tasks',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ExportRun',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('finished_at', models.DateTimeField(editable=False, null=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('job',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='jobs.Job')),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='runs',
                                           to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'export_runs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ExportTask',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('celery_uid', models.UUIDField(null=True)),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(blank=True, db_index=True, max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('started_at', models.DateTimeField(editable=False, null=True)),
                ('finished_at', models.DateTimeField(editable=False, null=True)),
            ],
            options={
                'ordering': ['created_at'],
                'db_table': 'export_tasks',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ExportTaskException',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('exception', models.TextField(editable=False)),
            ],
            options={
                'db_table': 'export_task_exceptions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ExportTaskResult',
            fields=[
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True,
                                              related_name='result', serialize=False, to='tasks.ExportTask')),
                ('filename', models.CharField(blank=True, editable=False, max_length=100)),
                ('size', models.FloatField(editable=False, null=True)),
                ('download_url', models.URLField(max_length=254, verbose_name='Url to export task result output.')),
            ],
            options={
                'db_table': 'export_task_results',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='exporttaskexception',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions',
                                    to='tasks.ExportTask'),
        ),
        migrations.AddField(
            model_name='exporttask',
            name='export_provider_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks',
                                    to='tasks.ExportProviderTask'),
        ),
        migrations.AddField(
            model_name='exportprovidertask',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_tasks',
                                    to='tasks.ExportRun'),
        ),
    ]
