# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-07 12:13


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20160919_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportprovidertask',
            name='status',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
    ]
