# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-27 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_exportprovidertask_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='exporttask',
            name='progress',
            field=models.IntegerField(default=0, editable=False, null=True),
        ),
    ]
