# Generated by Django 2.2.3 on 2019-09-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_dataprovidertaskrecord_estimated_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataprovidertaskrecord',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='exporttaskrecord',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
