# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-28 16:20


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_exportprovidertask_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='exporttask',
            name='estimated_finish',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='exporttask',
            name='progress',
            field=models.IntegerField(default=0, editable=False, null=True),
        ),
    ]
