# Generated by Django 2.2.5 on 2019-11-08 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', 'add_map_image_snapshot'),
        ('tasks', '0004_auto_20190913_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataprovidertaskrecord',
            name='preview',
            field=models.ForeignKey(blank=True, help_text='A preview for a provider task.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.MapImageSnapshot'),
        ),
    ]
