# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-01 21:25


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20161028_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportrun',
            name='zipfile_url',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
