# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-02 12:51


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_exportrun_zipfile_url'),
        ('tasks', '0005_exportrun_worker'),
    ]

    operations = [
    ]
