# Generated by Django 2.2.5 on 2020-05-12 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_dataprovider_label'),
        ('tasks', '0005_dataprovidertaskrecord_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataprovidertaskrecord',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_record_provider', to='jobs.DataProvider'),
        ),
    ]
