# Generated by Django 2.2.5 on 2020-05-16 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_dataprovidertaskrecord_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportrun',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
