# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-05 16:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0006_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='exporttask',
            name='cancel_user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exporttask',
            name='pid',
            field=models.IntegerField(blank=True, default=-1, editable=False),
        ),
        migrations.AddField(
            model_name='exporttask',
            name='worker',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
    ]
