# Generated by Django 2.2.5 on 2020-05-12 15:18

from django.db import migrations

from eventkit_cloud.jobs.models import DataProvider
from eventkit_cloud.tasks.models import DataProviderTaskRecord

def set_provider_from_slug(apps, schema_editor):
    task_records = DataProviderTaskRecord.objects.all()
    for task_record in task_records:
        try:
            task_record.provider = DataProvider.objects.get(slug=task_record.slug)
            task_record.save()
        except DataProvider.DoesNotExist:
            if task_record.slug != "run":
                print(f"{task_record.slug} does not map to any known DataProvider.")

def reverse_set_provider_from_slug(apps, schema_editor):
    task_records = DataProviderTaskRecord.objects.all()
    for task_record in task_records:
        task_record.provider = None
        task_record.save()

class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_dataprovidertaskrecord_provider'),
    ]

    operations = [
        migrations.RunPython(code=set_provider_from_slug, reverse_code=reverse_set_provider_from_slug)
    ]
