# Generated by Django 2.2.5 on 2020-08-12 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20200803_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataprovidertaskrecord',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_provider_task_records', to='tasks.ExportRun'),
        ),
    ]
