# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-30 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportprovidertask',
            name='celery_uid',
            field=models.UUIDField(null=True),
        ),
    ]
