# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-21 20:21


from django.db import migrations

import eventkit_cloud.jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20161206_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportprovidertask',
            name='slug',
            field=eventkit_cloud.jobs.models.LowerCaseCharField(default='', max_length=40),
        ),
    ]
