# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-22 12:49


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_exportrun_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportrun',
            name='notified',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
