# Generated by Django 3.2 on 2021-08-30 19:47

from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_add_use_bbox_data_providers'),
        ('tasks', '0008_exporttaskrecord_hide_download'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataprovidertaskrecord',
            name='started_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='exportrun',
            name='started_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='exportrunfile',
            name='file',
            field=models.FileField(storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to='', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='exporttaskrecord',
            name='started_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='runzipfile',
            name='started_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='dataprovidertaskrecord',
            unique_together={('provider', 'run')},
        ),
        migrations.AlterUniqueTogether(
            name='exporttaskrecord',
            unique_together={('name', 'export_provider_task')},
        ),
    ]
