# Generated by Django 3.2 on 2021-08-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_exporttaskrecord_hide_download'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataprovidertaskrecord',
            name='started_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='exportrun',
            name='started_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='exporttaskrecord',
            name='started_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='runzipfile',
            name='started_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
