# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-22 20:56


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_exportrun_notified'),
        ('tasks', '0008_exportprovidertask_slug'),
    ]

    operations = [
    ]
