# Generated by Django 3.2 on 2021-09-15 19:25

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_auto_20210830_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportrun',
            name='is_cloning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exportrun',
            name='parent_run',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='exportrunfile',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/export_run_files/', location='/var/lib/eventkit/exports_stage/export_run_files'), upload_to='', verbose_name='File'),
        ),
    ]
