# Generated by Django 2.2.5 on 2020-06-04 23:08

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_exportrunfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportrunfile',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/export_run_files/', location='/var/lib/eventkit/exports_stage/export_run_files'), upload_to='', verbose_name='File'),
        ),
    ]
