# Generated by Django 3.2 on 2021-08-24 00:18

from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_add_use_bbox_data_providers'),
        ('tasks', '0009_auto_20210811_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportrunfile',
            name='file',
            field=models.FileField(storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to='', verbose_name='File'),
        ),
        migrations.AlterUniqueTogether(
            name='dataprovidertaskrecord',
            unique_together={('provider', 'run')},
        ),
        migrations.AlterUniqueTogether(
            name='exporttaskrecord',
            unique_together={('name', 'export_provider_task')},
        ),
    ]
