# Generated by Django 3.2 on 2021-09-16 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_auto_20210915_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportrun',
            name='parent_run',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_runs', to='tasks.exportrun'),
        ),
    ]
