# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-22 21:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_finalizerunhooktaskrecord'),
        ('tasks', '0011_auto_20170607_0047'),
    ]

    operations = [
    ]
