# Generated by Django 4.0.4 on 2022-08-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_auto_20220322_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileproducingtaskresult',
            name='directory',
            field=models.CharField(blank=True, help_text='An optional directory name to store the file in.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fileproducingtaskresult',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='exportrunfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='fileproducingtaskresult',
            name='download_url',
            field=models.URLField(blank=True, null=True, max_length=508),
        )
    ]
