# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 20:05


import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0012_auto_20170624_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalizeRunHookTaskRecord',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('celery_uid', models.UUIDField()),
                ('task_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('started_at', models.DateTimeField(editable=False, null=True)),
                ('finished_at', models.DateTimeField(editable=False, null=True)),
                ('status', models.CharField(blank=True, db_index=True, max_length=20)),
                ('pid', models.IntegerField(blank=True, default=-1)),
                ('worker', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('cancel_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.ExportRun')),
            ],
            options={
                'ordering': ['created_at'],
                'db_table': 'finalize_run_hook_task_record',
                'managed': True,
            },
        ),
    ]
