# Generated by Django 3.2.7 on 2022-03-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_auto_20220314_1951'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exporttaskrecord',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='exporttaskrecord',
            constraint=models.UniqueConstraint(fields=('name', 'export_provider_task'), name='unique_name_export_provider_task'),
        ),
    ]
