# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-22 23:58


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_auto_20170622_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='exporttask',
            name='new_result',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_task', to='tasks.FileProducingTaskResult'),
        ),
        migrations.AddField(
            model_name='fileproducingtaskresult',
            name='id',
            field=models.IntegerField(null=True),
        ),
    ]
