# Generated by Django 4.0.4 on 2022-08-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_auto_20220803_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileproducingtaskresult',
            name='download_url',
        ),
        migrations.AddField(
            model_name='exportrunfile',
            name='filename',
            field=models.CharField(blank=True, editable=False, max_length=508),
        ),
        migrations.AddField(
            model_name='exportrunfile',
            name='size',
            field=models.FloatField(editable=False, null=True),
        ),
    ]
