# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-23 00:11


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_auto_20170622_2359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exporttask',
            old_name='new_result',
            new_name='result',
        ),
        migrations.RemoveField(
            model_name='fileproducingtaskresult',
            name='task',
        ),
        migrations.AlterField(
            model_name='fileproducingtaskresult',
            name='id',
            field=models.AutoField(primary_key=True, editable=False, serialize=False),
        ),
    ]
