# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-02 12:34


import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_populate_uuid_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalizerunhooktaskrecord',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
