# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-22 18:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_auto_20170802_1234'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExportProviderTask',
            new_name='DataProviderTaskRecord',
        ),
        migrations.RenameField(
            model_name='exporttask',
            old_name='export_provider_task',
            new_name='data_provider_task',
        ),
        migrations.AlterModelTable(
            name='dataprovidertaskrecord',
            table='data_provider_tasks',
        ),
    ]
