# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-15 16:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0023_auto_20170825_1416'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExportProviderTask',
            new_name='DataProviderTaskRecord',
        ),
        migrations.RenameModel(
            old_name='ExportTask',
            new_name='ExportTaskRecord',
        ),
        migrations.AlterModelTable(
            name='dataprovidertaskrecord',
            table='data_provider_task_records',
        ),
        migrations.AlterModelTable(
            name='exporttaskrecord',
            table='export_task_records',
        ),
    ]
