# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-20 16:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0024_auto_20171115_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exporttaskrecord',
            name='progress',
        ),
    ]
