# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-25 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0024_auto_20171115_1653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exportrun',
            options={'managed': True, 'verbose_name': 'ExportRun (DataPack)', 'verbose_name_plural': 'ExportRuns (DataPacks)'},
        ),
        migrations.RemoveField(
            model_name='exporttaskrecord',
            name='progress',
        ),
        migrations.AlterField(
            model_name='exporttaskrecord',
            name='status',
            field=models.CharField(db_index=True, default=b'PENDING', max_length=20),
        ),
    ]
