# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-06-19 13:15


import os
import uuid

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

download_url_root = settings.EXPORT_MEDIA_ROOT


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0026_auto_20181018_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileproducingtaskresult',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, db_index=True, unique=True)
        ),
        migrations.AlterField(
            model_name='fileproducingtaskresult',
            name='download_url',
            field=models.URLField(max_length=506, verbose_name='URL to export task result output.'),
        ),
        migrations.AddField(
            model_name='userdownload',
            name='downloadable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='tasks.FileProducingTaskResult'),
        ),
        migrations.AddField(
            model_name='userdownload',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exportrun',
            name='downloadable',
            field=models.OneToOneField(related_name='run', null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='tasks.FileProducingTaskResult'),
        ),
    ]
