# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-06-19 13:15


import os
import uuid

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

download_url_root = settings.EXPORT_MEDIA_ROOT

def update_run_downloads(apps, schema_editor):
    ExportRun = apps.get_model('tasks', 'ExportRun')
    FileProducingTaskResult = apps.get_model('tasks', 'FileProducingTaskResult')
    for run in ExportRun.objects.all():

        zipfile_url = run.zipfile_url
        if zipfile_url:
            downloadable = FileProducingTaskResult.objects.create(
                download_url=os.path.join(download_url_root, zipfile_url))
            run.downloadable = downloadable
            run.save()

def reverse_run_downloads(apps, schema_editor):
    # if jobs were made public then they should be set to published.
    ExportRun = apps.get_model('tasks', 'ExportRun')
    for run in ExportRun.objects.all():
        run.zipfile_url = run.downloadable.download_url.lstrip(download_url_root)

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0026_auto_20181018_2151'),
    ]

    operations = [
        migrations.RunPython(update_run_downloads, reverse_code=reverse_run_downloads),
    ]
