# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-06-19 13:15


import os
import uuid

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

download_url_root = settings.EXPORT_MEDIA_ROOT

def create_uuid(apps, schema_editor):
    FileProducingTaskResult = apps.get_model('tasks', 'FileProducingTaskResult')
    for downloadable in FileProducingTaskResult.objects.all():
        downloadable.uid = uuid.uuid4()
        downloadable.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0026_auto_20180619_1315'),
    ]

    operations = [
        migrations.RunPython(create_uuid),
    ]
