# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-20 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0025_remove_exporttaskrecord_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exporttaskrecord',
            name='status',
            field=models.CharField(db_index=True, default=b'PENDING', max_length=20),
        ),
    ]
