# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-06-19 13:15


import os
import uuid

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

download_url_root = settings.EXPORT_MEDIA_ROOT


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0026_auto_20181018_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exportrun',
            name='zipfile_url',
        ),
        migrations.AlterField(
            model_name='fileproducingtaskresult',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
