# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-06-25 15:19


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0026_auto_20180619_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileproducingtaskresult',
            name='download_url',
            field=models.URLField(max_length=508, verbose_name='URL to export task result output.'),
        ),
        migrations.AlterField(
            model_name='fileproducingtaskresult',
            name='filename',
            field=models.CharField(blank=True, editable=False, max_length=508),
        ),
    ]
