# Generated by Django 2.0.8 on 2018-10-30 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0028_auto_20180724_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exporttaskrecord',
            name='estimated_finish',
        ),
        migrations.RemoveField(
            model_name='exporttaskrecord',
            name='progress',
        ),
    ]
