# Generated by Django 2.0.9 on 2018-12-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0029_auto_20181030_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataprovidertaskrecord',
            name='estimated_size',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
