# Generated by Django 2.2.5 on 2019-11-27 14:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventkit_cloud_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauth',
            name='user_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
