# Generated by Django 2.2.3 on 2019-09-17 13:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventkit_cloud.auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauth',
            name='user_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
