# Generated by Django 3.1.2 on 2021-05-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventkit_cloud_auth', '0002_auto_20191127_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauth',
            name='user_info',
            field=models.JSONField(default=dict),
        ),
    ]
