# Generated by Django 3.2.7 on 2021-10-14 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventkit_cloud_auth', '0004_usersession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauth',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
