{% set name = "eventkit-cloud" %}
{% set version = "1.9.0" %}

{% set run_requirements = load_file_regex(
    load_file="conda-requirements.txt",
    regex_pattern=".+",
    from_recipe_dir=True).string.strip().split("\n")
%}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"
source:
  git_url: /eventkit-cloud
build:
  number: '{{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}'
requirements:
  build:
    - git
  host:
    - python >=3.7,<3.8
    - pip
    - nodejs>=10
    - ruby
  run_constrained:
    - memcached=1.6.6
    - qgis=3.14.16
  run:
    {% for req in run_requirements -%}
      - {{ req }}
    {% endfor %}
    - python >=3.7,<3.8
    - libiconv=1.15
    - mesa-libgl-cos7-x86_64
    - osmctools=0.9.0
    - proj=7.1.1
    - zstd=1.4.5
about:
  home: https://github.com/eventkit/eventkit-cloud
  license: BSD 3-Clause
  license_family: BSD
  license_file: /eventkit-cloud/LICENSE.md
  summary: 'A tool for packaging and sharing data from various web services.'
  description: "Eventkit-cloud is based on the HOT OSM Export Tool 2. It allows the user to select data from different sources to export into a variety of formats."
  doc_url: 'https://github.com/eventkit/eventkit-cloud/blob/master/readme.md'
  dev_url: 'https://github.com/eventkit/eventkit-cloud'
extra:
  recipe-maintainers:
    - jsvrcek
