{% set name = "eventkit-cloud" %}
{% set version = "1.9.0" %}
package:
  name: "{{ name|lower }}"
  version: "{{ version }}"
source:
  git_url: /eventkit-cloud
build:
  number: '{{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}'
requirements:
  build:
    - git
  host:
    - python >=3.7,<3.8
    - pip
    - nodejs>=10
    - ruby
  run_constrained:
    - memcached=1.6.6
    - qgis=3.14.16
  run:
    - python >=3.7,<3.8
    - billiard=3.6.3.0
    - boto3=1.14.15
    - celery=4.4.6
    - dj-database-url=0.5.0
    - django=3.1.2
    - django-audit-logging=0.2.1
    - django-auth-ldap=2.2.0
    - django-celery-beat=2.0.0
    - django-extensions=3.0.9
    - django-filter=2.4.0
    - django-notifications-hq=1.6.0
    - django-storages=1.9.1
    - django-timezone-field=4.0
    - djangorestframework=3.12.1
    - djangorestframework-gis=0.15.0
    - eventlet=0.28.0
    - gdal=3.1.4
    - gunicorn=20.0.4
    - libiconv=1.15
    - mapproxy=1.12.0
    - mesa-libgl-cos7-x86_64
    - numpy=1.19.2
    - osmctools=0.9.0
    - pillow=8.0.1
    - proj=7.1.1
    - psycopg2=2.8.4
    - pyjwt=1.7.1
    - pyparsing=2.4.7
    - python-dateutil=2.8.1
    - python-ldap=3.2.0
    - python-magic=0.4.15
    - python-memcached=1.59
    - pytz=2020.1
    - pyyaml=5.3.1
    - requests=2.24.0
    - shapely=1.7.1
    - sqlparse=0.3.1
    - swapper=1.1.2.post1
    - uritemplate=3.0.1
    - webtest=2.0.35
    - whitenoise=4.1.4
    - zstd=1.4.5
about:
  home: https://github.com/eventkit/eventkit-cloud
  license: BSD 3-Clause
  license_family: BSD
  license_file: /eventkit-cloud/LICENSE.md
  summary: 'A tool for packaging and sharing data from various web services.'
  description: "Eventkit-cloud is based on the HOT OSM Export Tool 2. It allows the user to select data from different sources to export into a variety of formats."
  doc_url: 'https://github.com/eventkit/eventkit-cloud/blob/master/readme.md'
  dev_url: 'https://github.com/eventkit/eventkit-cloud'
extra:
  recipe-maintainers:
    - jsvrcek