{% set name = "eventkit-cloud" %}
{% set version = "1.6.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: /eventkit-cloud

build:
  number: '{{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}'

requirements:
  build:
    - python =3.6
    - pip
    - setuptools
    - wheel
    - nodejs
    - ruby
    - git
    - django-audit-logging =0.2.1
    - gdal =2.4.1
    - osmctools =0.7.0
    - openldap =2.4.46
    - python-ldap =3.1.0
    - amqp =2.4.2
    - billiard =3.5.0.4
    - boto3 =1.9.141
    - celery =4.2.1
    - certifi =2019.3.9
    - django =2.2.5
    - dj-database-url =0.4.2
    - django-auth-ldap =1.7.0
    - django-celery-beat =1.4.0
    - django-celery-results =1.0.4
    - django-extensions =2.1.6
    - django-filter =2.2.0
    - django-notifications-hq =1.5.0
    - django-storages =1.6.6
    - djangorestframework =3.11.0
    - djangorestframework-gis =0.14
    - eventlet =0.23.0
    - gunicorn =19.9.0
    - kombu =4.2.1
    - lxml =4.3.3
    - MapProxy =1.12.0
    - Markdown =3.1
    - numpy =1.16.3
    - Pillow =6.0.0
    - psycopg2 =2.8.2
    - PyJWT =1.7.1
    - pyparsing =2.4.0
    - python-dateutil =2.8.0
    - python-magic =0.4.15
    - python-memcached =1.59
    - pytz =2019.1
    - PyYAML =5.1
    - requests =2.21.0
    - Shapely =1.6.4
    - simplejson =3.16.0
    - sqlparse =0.3.0
    - uritemplate =3.0.1
    - webtest =2.0.33
    - whitenoise =4.1.2
  run:
    - python =3.6
    - django-audit-logging =0.2.1
    - gdal =2.4.1
    - osmctools =0.7.0
    - openldap =2.4.46
    - python-ldap =3.1.0
    - amqp =2.4.2
    - billiard =3.5.0.4
    - boto3 =1.9.141
    - celery =4.2.1
    - certifi =2019.3.9
    - django =2.2.5
    - dj-database-url =0.4.2
    - django-auth-ldap =1.7.0
    - django-celery-beat =1.4.0
    - django-celery-results =1.0.4
    - django-extensions =2.1.6
    - django-filter =2.2.0
    - django-notifications-hq =1.5.0
    - django-storages =1.6.6
    - djangorestframework =3.11.0
    - djangorestframework-gis =0.14
    - eventlet =0.23.0
    - gunicorn =19.9.0
    - kombu =4.2.1
    - lxml =4.3.3
    - MapProxy =1.12.0
    - Markdown =3.1
    - numpy =1.16.3
    - Pillow =6.0.0
    - psycopg2 =2.8.2
    - PyJWT =1.7.1
    - pyparsing =2.4.0
    - python-dateutil =2.8.0
    - python-magic =0.4.15
    - python-memcached =1.59
    - pytz =2019.1
    - PyYAML =5.1
    - requests =2.21.0
    - Shapely =1.6.4
    - simplejson =3.16.0
    - sqlparse =0.3.0
    - uritemplate =3.0.1
    - webtest =2.0.33
    - whitenoise =4.1.2

about:
  home: https://github.com/eventkit/eventkit-cloud
  license: BSD 3-Clause
  license_family: BSD
  license_file: /eventkit-cloud/LICENSE.md
  summary: 'A tool for packaging and sharing data from various web services.'
  description: "Eventkit-cloud is based on the HOT OSM Export Tool 2. It allows the user to select data from different sources to export into a variety of formats."
  doc_url: 'https://github.com/eventkit/eventkit-cloud/blob/master/readme.md'
  dev_url: 'https://github.com/eventkit/eventkit-cloud'

extra:
  recipe-maintainers:
    - jsvrcek
