{% set name = "eventkit-cloud" %}
{% set version = "1.10.0" %}

{% set run_requirements = load_file_regex(
    load_file="conda-requirements.txt",
    regex_pattern=".+",
    from_recipe_dir=True).string.strip().split("\n")
%}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"
source:
  git_url: /eventkit-cloud
build:
  number: '{{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}'

requirements:
  host:
    - git
    - pip=21.1
    - python >=3.9,<3.10
    - nodejs>=10
    - ruby
  run_constrained:
    - memcached=1.6.9
    - qgis
    - postgresql=12.3
  run:
    - python >=3.9,<3.10
    - mesa-libgl-cos7-x86_64
    - osmctools=0.9.0
    - proj=7.1.1
    {% for req in run_requirements -%}
      - {{ req }}
    {% endfor %}
    # Forces correct dependency resolution
    - expat >=2.2.10,<2.3.0a0
about:
  home: https://github.com/eventkit/eventkit-cloud
  license: BSD 3-Clause
  license_family: BSD
  license_file: /eventkit-cloud/LICENSE.md
  summary: 'A tool for packaging and sharing data from various web services.'
  description: "Eventkit-cloud is based on the HOT OSM Export Tool 2. It allows the user to select data from different sources to export into a variety of formats."
  doc_url: 'https://github.com/eventkit/eventkit-cloud/blob/master/readme.md'
  dev_url: 'https://github.com/eventkit/eventkit-cloud'
extra:
  recipe-maintainers:
    - jsvrcek

