{% set name = "eventkit-cloud" %}
{% set version = "1.8.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: /eventkit-cloud

build:
  number: '{{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}'

requirements:
  build:
    - python
    - pip
    - nodejs >=10
    - ruby
    - git
  run:
    - python
    - billiard
    - boto3
    - celery
    - dj-database-url
    - django
    - django-audit-logging
    - django-auth-ldap
    - django-celery-beat
    - django-extensions
    - django-filter
    - django-notifications-hq
    - django-storages
    - django-timezone-field
    - djangorestframework
    - djangorestframework-gis
    - eventlet
    - gdal
    - gunicorn
    - mapproxy
    - numpy
    - openldap
    - osmctools
    - pillow
    - proj
    - psycopg2
    - pyjwt
    - pyparsing
    - python-dateutil
    - python-ldap
    - python-magic
    - python-memcached
    - pytz
    - pyyaml
    - qgis
    - requests
    - shapely
    - sqlparse
    - swapper
    - uritemplate
    - webtest
    - whitenoise
about:
  home: https://github.com/eventkit/eventkit-cloud
  license: BSD 3-Clause
  license_family: BSD
  license_file: /eventkit-cloud/LICENSE.md
  summary: 'A tool for packaging and sharing data from various web services.'
  description: "Eventkit-cloud is based on the HOT OSM Export Tool 2. It allows the user to select data from different sources to export into a variety of formats."
  doc_url: 'https://github.com/eventkit/eventkit-cloud/blob/master/readme.md'
  dev_url: 'https://github.com/eventkit/eventkit-cloud'

extra:
  recipe-maintainers:
    - jsvrcek
