{% set name = "eventkit-cloud" %}
{% set version = "1.8.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: /eventkit-cloud

build:
  number: '{{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}'

requirements:
  build:
    - python
    - pip
    - setuptools
    - wheel
    - nodejs
    - ruby
    - git
  run:
    - python
    - django-audit-logging
    - gdal >=2.0.0
    - osmctools
    - openldap
    - python-ldap
    - amqp
    - billiard
    - boto3
    - celery
    - certifi
    - django
    - dj-database-url
    - django-auth-ldap
    - django-celery-beat
    - django-celery-results
    - django-extensions
    - django-filter
    - django-notifications-hq
    - django-storages
    - djangorestframework
    - djangorestframework-gis
    - eventlet
    - gunicorn
    - kombu
    - lxml
    - MapProxy
    - Markdown
    - numpy
    - Pillow
    - psycopg2
    - PyJWT
    - pyparsing
    - python-dateutil
    - python-magic
    - python-memcached
    - pytz
    - PyYAML
    - requests
    - Shapely
    - simplejson
    - sqlparse
    - uritemplate
    - webtest
    - whitenoise

about:
  home: https://github.com/eventkit/eventkit-cloud
  license: BSD 3-Clause
  license_family: BSD
  license_file: /eventkit-cloud/LICENSE.md
  summary: 'A tool for packaging and sharing data from various web services.'
  description: "Eventkit-cloud is based on the HOT OSM Export Tool 2. It allows the user to select data from different sources to export into a variety of formats."
  doc_url: 'https://github.com/eventkit/eventkit-cloud/blob/master/readme.md'
  dev_url: 'https://github.com/eventkit/eventkit-cloud'

extra:
  recipe-maintainers:
    - jsvrcek
