{% set name = "eventkit-cloud" %}
{% set version = "1.8.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: /eventkit-cloud

build:
  number: '{{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}'

requirements:
  build:
    - python
    - pip
    - setuptools
    - wheel
    - nodejs
    - ruby
    - git
  run:
    - python =3.7
    - gdal =3.1.2
    - osmctools =0.9.0
    - openldap =2.4.46
    - python-ldap =3.2.0
    - billiard =3.6.3.0
    - boto3 =1.14.15
    - celery =4.4.6
    - django =3.0.8
    - dj-database-url =0.5.0
    - django-audit-logging =0.2.1
    - django-auth-ldap =2.2.0
    - django-celery-beat =2.0.0
    - django-extensions =3.0.2
    - django-filter =2.3.0
    - django-notifications-hq =1.6.0
    - django-storages =1.9.1
    - djangorestframework =3.11.0
    - djangorestframework-gis =0.15.0
    - eventlet =0.26.1
    - gunicorn =20.0.4
    - MapProxy =1.12.0
    - numpy =1.18.5
    - Pillow =7.1.2
    - psycopg2 =2.8.4
    - PyJWT =1.7.1
    - pyparsing =2.4.7
    - python-dateutil =2.8.1
    - python-magic =0.4.15
    - python-memcached =1.59
    - pytz =2020.1
    - PyYAML =5.3.1
    - requests =2.24.0
    - Shapely =1.6.4
    - sqlparse =0.3.1
    - uritemplate =3.0.1
    - webtest =2.0.35
    - whitenoise =4.1.4

about:
  home: https://github.com/eventkit/eventkit-cloud
  license: BSD 3-Clause
  license_family: BSD
  license_file: /eventkit-cloud/LICENSE.md
  summary: 'A tool for packaging and sharing data from various web services.'
  description: "Eventkit-cloud is based on the HOT OSM Export Tool 2. It allows the user to select data from different sources to export into a variety of formats."
  doc_url: 'https://github.com/eventkit/eventkit-cloud/blob/master/readme.md'
  dev_url: 'https://github.com/eventkit/eventkit-cloud'

extra:
  recipe-maintainers:
    - jsvrcek
