{% set name = "eventkit-cloud" %}
{% set version = "1.14.0" %}

{% set run_requirements = load_file_regex(
    load_file="conda-requirements.txt",
    regex_pattern=".+",
    from_recipe_dir=True).string.strip().split("\n")
%}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"
source:
  path: /eventkit-cloud
build:
  number: 3

requirements:
  build:
    - git
    - pip {% if pip is defined %} {{ pip }} {% endif %}
    - python {% if python is defined %} {{ python }} {% endif %}
    - nodejs>=16
    - ruby
  run_constrained:
    - memcached {% if memcached is defined %} {{ memcached }} {% endif %}
    - qgis
  run:
    - python {% if python is defined %} {{ python }} {% endif %}
    - mesa-libgl-cos7-x86_64
    - osmctools {% if osmctools is defined %} {{ osmctools }} {% endif %}
    - proj {% if proj is defined %} {{ proj }} {% endif %}
    {% for req in run_requirements -%}
      - {{ req }}
    {% endfor %}
about:
  home: https://github.com/eventkit/eventkit-cloud
  license: BSD 3-Clause
  license_family: BSD
  license_file: /eventkit-cloud/LICENSE.md
  summary: 'A tool for packaging and sharing data from various web services.'
  description: "Eventkit-cloud is based on the HOT OSM Export Tool 2. It allows the user to select data from different sources to export into a variety of formats."
  doc_url: 'https://github.com/eventkit/eventkit-cloud/blob/master/readme.md'
  dev_url: 'https://github.com/eventkit/eventkit-cloud'
extra:
  recipe-maintainers:
    - jsvrcek
