{% set name = "gdalutils" %}
{% set version = "1.0.5" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "c72e9eab308c44dfea4a47a21b3c3dda8d4ba7ed8e57b82da645189fd3ba9970" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://github.com/eventkit/{{ name }}/archive/{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value|lower }}'

build:
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {% if python is defined %} {{ python }} {% endif %}
    - pip {% if pip is defined %} {{ pip }} {% endif %}
  run:
    - python {% if python is defined %} {{ python }} {% endif %}
    - pyproj {% if pyproj is defined %} {{ pyproj }} {% endif %}
    - gdal {% if gdal is defined %} {{ gdal }} {% endif %}
    - pip {% if pip is defined %} {{ pip }} {% endif %}

test:
  imports:
    - gdal_utils

about:
  home: https://github.com/eventkit/gdalutils
  summary: 'gdalutils'
  description: 'This package includes various utilities for using gdal for geospatial data processing.'
  doc_url: 'https://github.com/EventKit/gdalutils/blob/main/README.md'
  dev_url: 'https://github.com/eventkit/gdalutils'

extra:
  recipe-maintainers:
    - coop56
