# Generated by Django 2.2.5 on 2020-03-30 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
        ('jobs', 'add_map_image_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMaxDataSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_data_size', models.DecimalField(decimal_places=3, default=100, help_text='This is the maximum data size in MB that can be exported from this provider in a single DataPack.', max_digits=12, verbose_name='Max data size')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.DataProvider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupMaxDataSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_data_size', models.DecimalField(decimal_places=3, default=100, help_text='This is the maximum data size in MB that can be exported from this provider in a single DataPack.', max_digits=12, verbose_name='Max data size')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.DataProvider')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
