# Generated by Django 2.0.9 on 2018-12-13 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        ('auth', '0009_alter_user_last_name_max_length'),
        ('jobs', 'load_regions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='last_export_run',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_export_run', to='tasks.ExportRun'),
        ),
        migrations.AddField(
            model_name='job',
            name='preset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.DatamodelPreset'),
        ),
        migrations.AddField(
            model_name='job',
            name='provider_tasks',
            field=models.ManyToManyField(related_name='provider_tasks', to='jobs.DataProviderTask'),
        ),
        migrations.AddField(
            model_name='job',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.Region'),
        ),
        migrations.AddField(
            model_name='job',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exportprofile',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='export_profile', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='dataprovidertype',
            name='supported_formats',
            field=models.ManyToManyField(blank=True, to='jobs.ExportFormat', verbose_name='Supported Export Formats'),
        ),
        migrations.AddField(
            model_name='dataprovidertask',
            name='formats',
            field=models.ManyToManyField(related_name='formats', to='jobs.ExportFormat'),
        ),
        migrations.AddField(
            model_name='dataprovidertask',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider', to='jobs.DataProvider'),
        ),
        migrations.AddField(
            model_name='dataproviderstatus',
            name='related_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_provider_status', to='jobs.DataProvider'),
        ),
        migrations.AddField(
            model_name='dataprovider',
            name='export_provider_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.DataProviderType', verbose_name='Service Type'),
        ),
        migrations.AddField(
            model_name='dataprovider',
            name='license',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='jobs.License'),
        ),
        migrations.AddField(
            model_name='dataprovider',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
