# Generated by Django 2.2.5 on 2020-07-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('jobs', '0002_auto_20200604_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpermission',
            name='permission',
            field=models.CharField(choices=[('READ', 'Read'), ('ADMIN', 'Admin')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='jobpermission',
            unique_together={('job', 'content_type', 'object_id', 'permission')},
        ),
    ]
