# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-20 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportprovidertype',
            name='type_name',
            field=models.CharField(default='', max_length=6, unique=True, verbose_name='Type Name'),
        ),
    ]
