# Generated by Django 2.2.5 on 2020-06-04 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20200604_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataprovider',
            name='attribute_class',
            field=models.ForeignKey(blank=True, help_text='The attribute class is used to limit users access to resources using this data provider.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_providers', to='core.AttributeClass'),
        ),
    ]
