# Generated by Django 2.2.5 on 2020-08-13 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataprovidertask',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_provider_tasks', to='jobs.Job'),
        ),
        migrations.AlterField(
            model_name='dataprovidertask',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_provider', to='jobs.DataProvider'),
        ),
    ]
