# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-30 23:53


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20161024_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='zipfile_url',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
