# Generated by Django 3.0.8 on 2020-08-31 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_remove_job_provider_tasks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegionMask',
        ),
        migrations.RemoveField(
            model_name='job',
            name='region',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
