# Generated by Django 3.0.8 on 2020-09-29 12:17

from django.db import migrations

import eventkit_cloud.jobs.models


class Migration(migrations.Migration):
    def insert_export_formats(apps, schema_editor):  # NOQA
        DataProviderType = apps.get_model("jobs", "DataProviderType")  # NOQA
        ExportFormat = apps.get_model("jobs", "ExportFormat")  # NOQA
        Projection = apps.get_model("jobs", "Projection")

        # New Formats.
        mbtiles, created = ExportFormat.objects.get_or_create(
            name="MBTiles Format", description="MBTiles", slug="mbtiles"
        )
        gpx, created = ExportFormat.objects.get_or_create(
            name="GPX Format", description="GPS Exchange Format", slug="gpx"
        )
        sqlite = ExportFormat.objects.get(slug="sqlite")

        # Currently available Provider Types.
        vector_data_provider_types = ["osm", "osm-generic", "wfs", "arcgis-feature"]
        raster_data_provider_types = ["tms", "arcgis-raster", "wmts", "wms"]

        # Set the known supported export formats per provider type.
        for provider_type in DataProviderType.objects.all():
            if provider_type.type_name in vector_data_provider_types:
                provider_type.supported_formats.add(sqlite, gpx)
            if provider_type.type_name in raster_data_provider_types:
                provider_type.supported_formats.add(mbtiles)

        projection_4326 = Projection.objects.get(srid=4326)
        projection_3857 = Projection.objects.get(srid=3857)

        mbtiles.supported_projections.add(projection_3857)
        sqlite.supported_projections.add(projection_4326, projection_3857)
        gpx.supported_projections.add(projection_4326, projection_3857)

    def remove_export_formats(apps, schema_editor):  # NOQA
        ExportFormat = apps.get_model("jobs", "ExportFormat")  # NOQA
        ExportFormat.objects.filter(slug="mbtiles").delete()
        ExportFormat.objects.filter(slug="sqlite").delete()
        ExportFormat.objects.filter(slug="gpx").delete()

    dependencies = [
        ("jobs", "0006_remove_job_provider_tasks"),
    ]

    operations = [
        migrations.RunPython(insert_export_formats, remove_export_formats),
    ]
