# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-01 21:25


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_include_zipfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='zipfile_url',
        ),
    ]
