# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-15 16:12


import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0007_remove_job_zipfile_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportprovider',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
