# Generated by Django 3.0.8 on 2020-09-03 21:00

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_remove_region_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('bounding_box', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('policies', django.contrib.postgres.fields.jsonb.JSONField()),
                ('policy_title_text', models.CharField(max_length=100)),
                ('policy_header_text', models.TextField(blank=True, null=True)),
                ('policy_footer_text', models.TextField(blank=True, null=True)),
                ('policy_cancel_text', models.CharField(blank=True, max_length=100, null=True)),
                ('policy_cancel_button_text', models.CharField(max_length=100)),
                ('justification_options', django.contrib.postgres.fields.jsonb.JSONField()),
                ('providers', models.ManyToManyField(related_name='region_providers', to='jobs.DataProvider')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
