# Generated by Django 3.0.8 on 2020-09-14 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0007_regionalpolicy'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionalJustification',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('justification_id', models.IntegerField()),
                ('justification_name', models.CharField(max_length=100)),
                ('justification_description', models.CharField(blank=True, max_length=1000, null=True)),
                ('regional_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justifications', to='jobs.RegionalPolicy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justification_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
