# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-19 18:49


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_auto_20161216_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportprovider',
            name='preview_url',
            field=models.CharField(blank=True, default='', help_text='This url will be served to the front end for displaying in the map.', max_length=1000, null=True, verbose_name='Preview URL'),
        ),
        migrations.AddField(
            model_name='exportprovider',
            name='service_copyright',
            field=models.CharField(blank=True, default='', help_text='This information is used to display relevant copyright information.', max_length=2000, null=True, verbose_name='Copyright'),
        ),
    ]
