# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-06 14:18


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_auto_20170119_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportprovider',
            name='service_description',
            field=models.CharField(blank=True, default='', help_text='This information is used to provide information about the service.', max_length=4000, null=True, verbose_name='Description'),
        ),
    ]
