# Generated by Django 3.1.2 on 2021-04-07 21:23

from django.db import migrations


class Migration(migrations.Migration):
    def add_ogc_process_provider(apps, schema_editor):
        DataProviderType = apps.get_model('jobs', 'DataProviderType')
        ExportFormat = apps.get_model('jobs', 'ExportFormat')

        # Create the DataProvider objects if they don't exist.
        ogc_provider, _ = DataProviderType.objects.get_or_create(type_name='ogc-process')

        # Currently available Export Formats.
        gpkg = ExportFormat.objects.get(slug='gpkg')

        # Set the known supported export formats per provider type.
        ogc_provider.supported_formats.add(gpkg)

    dependencies = [
        ('jobs', '0011_add_file_data_providers'),
    ]

    operations = [
        migrations.RunPython(add_ogc_process_provider)
    ]
