# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_auto_20170306_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='json_filters',
            field=models.TextField(default='{}'),
        ),
    ]
