# Generated by Django 3.1.2 on 2021-02-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_add_file_data_providers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataprovider',
            name='max_selection',
            field=models.DecimalField(decimal_places=3, default=250, help_text='This is the maximum area in square kilometers that can be exported from this provider in a single DataPack.', max_digits=13, verbose_name='Max selection area'),
        ),
    ]
