# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 01:24


import django.contrib.postgres.fields.jsonb
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_auto_20170306_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatamodelPreset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('name', models.CharField(max_length=10)),
                ('json_tags', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
            options={
                'db_table': 'datamodel_preset',
            },
        ),
        migrations.AddField(
            model_name='job',
            name='json_tags',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.RemoveField(
            model_name='tag',
            name='job',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
