# Generated by Django 3.1.2 on 2021-05-04 14:00
from django.db import migrations


class Migration(migrations.Migration):

    def set_use_bbox(apps, schema_editor):
        DataProviderType = apps.get_model('jobs', 'DataProviderType')

        # Data provider types that can only fetch data from bbox
        bbox_data_provider_types = ['osm', 'osm-generic', 'wfs', 'arcgis-feature']

        # Set use bbox on all provider types
        for provider_type in DataProviderType.objects.all():
            provider_type.use_bbox = provider_type.type_name in bbox_data_provider_types

    def unset_use_bbox(apps, schema_editor):
        DataProviderType = apps.get_model('jobs', 'DataProviderType')

        for provider_type in DataProviderType.objects.all():
            provider_type.use_bbox = False

    dependencies = [
        ('jobs', '0012_dataprovidertype_use_bbox'),
    ]

    operations = [
        migrations.RunPython(set_use_bbox, unset_use_bbox),
    ]
