# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 18:38
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_auto_20170403_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='json_filters',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
