# Generated by Django 3.1.2 on 2021-05-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_add_ogc_process_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exportformat',
            name='cmd',
        ),
        migrations.AddField(
            model_name='exportformat',
            name='options',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='datamodelpreset',
            name='json_tags',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='job',
            name='json_tags',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='regionalpolicy',
            name='justification_options',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='regionalpolicy',
            name='policies',
            field=models.JSONField(),
        ),
    ]
