# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 15:04


import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import eventkit_cloud.jobs.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0013_auto_20170417_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', eventkit_cloud.jobs.models.LowerCaseCharField(default='', max_length=40, unique=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('text', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='UserLicenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.License')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='exportprovider',
            name='license',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='jobs.License'),
        ),
    ]
