# Generated by Django 3.1.2 on 2021-05-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_add_ogc_process_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataprovidertype',
            name='use_bbox',
            field=models.BooleanField(default=False, verbose_name='Use bounding box to calculate area'),
        ),
    ]
