# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_auto_20170405_2214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='json_filters',
            new_name='json_tags',
        ),
    ]
