# Generated by Django 3.2.7 on 2021-09-30 18:08

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.collections
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_auto_20210930_1808'),
        ('jobs', '0015_add_use_bbox_data_providers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='last_export_run',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_export_run', to='tasks.exportrun'),
        ),
        migrations.AlterField(
            model_name='job',
            name='original_selection',
            field=django.contrib.gis.db.models.fields.GeometryCollectionField(blank=True, default=django.contrib.gis.geos.collections.GeometryCollection, null=True, srid=4326, verbose_name='The original map selection'),
        ),
    ]
