# Generated by Django 3.2 on 2021-09-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_add_use_bbox_data_providers'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='properties',
            field=models.JSONField(default=dict),
        ),
    ]
