# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_auto_20170406_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='job',
        ),
        migrations.AlterField(
            model_name='exportprovider',
            name='config',
            field=models.TextField(blank=True, default='', help_text='This is an optional field to put in additional configuration.', null=True, verbose_name='Configuration'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
