# Generated by Django 3.2.7 on 2021-10-12 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_auto_20211004_1622'),
        ('jobs', '0017_auto_20211008_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='last_export_run',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_export_run', to='tasks.exportrun'),
        ),
    ]
