# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-26 16:27


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_exportprovider_display'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='feature_pub',
            new_name='featured',
        ),
        migrations.RemoveField(
            model_name='job',
            name='feature_save',
        ),
    ]
