# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-03 14:30


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_auto_20170802_1221'),
        ('jobs', '0019_auto_20170726_1627'),
    ]

    operations = [
    ]
