# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-22 18:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0020_merge_20170803_1430'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExportProvider',
            new_name='DataProvider',
        ),
        migrations.RenameModel(
            old_name='ProviderTask',
            new_name='DataProviderTask',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='provider_tasks',
            new_name='data_provider_tasks',
        ),
        migrations.AlterModelTable(
            name='dataprovider',
            table='data_provider',
        ),
    ]
