# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-13 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0023_auto_20171122_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.Region'),
        ),
    ]
