# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-15 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0024_auto_20180313_2039' )
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='visibility',
            field=models.CharField(default='PRIVATE', max_length=10),
        ),
    ]
