# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-11 20:16


import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0024_auto_20180313_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataProviderStatus',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(blank=True, max_length=10)),
                ('status_type', models.CharField(blank=True, max_length=25)),
                ('message', models.CharField(blank=True, max_length=150)),
                ('last_check_time', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ['-last_check_time'],
                'verbose_name_plural': 'data provider statuses',
            },
        ),
        migrations.AlterField(
            model_name='dataprovider',
            name='url',
            field=models.CharField(blank=True, default='', help_text='The SERVICE_URL is used as the endpoint for WFS, OSM, and WCS services. It is also used to check availability for all OGC services. If you are adding a TMS service, please provide a link to a single tile, but with the coordinate numbers replaced by {z}, {y}, and {x}. Example: https://tiles.your-geospatial-site.com/tiles/default/{z}/{y}/{x}.png', max_length=1000, null=True, verbose_name='Service URL'),
        ),
        migrations.AddField(
            model_name='dataproviderstatus',
            name='related_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_provider_status', to='jobs.DataProvider'),
        ),
    ]
