# Generated by Django 4.0.4 on 2022-07-18 15:06

from django.db import migrations, models
import django.utils.timezone
import eventkit_cloud.core.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0024_auto_20220609_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Topic Name')),
                ('slug', eventkit_cloud.core.models.LowerCaseCharField(default='', max_length=40, unique=True)),
                ('topic_description', models.TextField(blank=True, default='', help_text='This information is used to provide information about the Topic.', null=True, verbose_name='Description')),
                ('providers', models.ManyToManyField(related_name='topics', to='jobs.dataprovider')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
