# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-02 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0024_auto_20180313_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataprovider',
            name='url',
            field=models.CharField(blank=True, default='', help_text='The SERVICE_URL is used as the endpoint for WFS, OSM, and WCS services. It is also used to check availability for all OGC services. If you are adding a TMS service, please provide a link to a single tile, but with the coordinate numbers replaced by {z}, {y}, and {x}. Example: https://tiles.your-geospatial-site.com/tiles/default/{z}/{y}/{x}.png', max_length=1000, null=True, verbose_name='Service URL'),
        ),
    ]
