# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-04 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0025_auto_20180402_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='visibility',
            field=models.CharField(default='PRIVATE', max_length=10),
        ),
    ]
