# Generated by Django 4.0.4 on 2022-07-28 17:52

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0025_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='StyleFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/export_run_files/', location='/var/lib/eventkit/exports_stage/export_run_files'), upload_to='', verbose_name='File')),
                ('directory', models.CharField(blank=True, help_text='An optional directory name to store the file in.', max_length=100, null=True)),
                ('style_type', models.CharField(blank=True, choices=[('arcgis_layer', 'ArcGIS Layer'), ('qgis_layer', 'QGIS Layer'), ('mapbox', 'Mapbox'), ('sld', 'SLD'), ('kml', 'KML')], default='', help_text='The type of style provided (e.g. arcgis, qgis, mapbox)', max_length=20, null=True, verbose_name='Style Type')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='styles', to='jobs.dataprovider')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
