# Generated by Django 4.0.4 on 2022-06-30 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0026_auto_20220630_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataprovider',
            name='config',
        ),
        migrations.RenameField(
            model_name='dataprovider',
            old_name='config_json',
            new_name='config',
        ),
    ]
