# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-17 12:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0026_job_visibility'),
        ('jobs', '0025_auto_20180411_2016'),
    ]

    operations = [
    ]
