# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-17 17:23


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0027_merge_20180417_1210'),
        ('jobs', '0025_auto_20180412_2228'),
    ]

    operations = [
    ]
