# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-18 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0027_merge_20180417_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataproviderstatus',
            name='related_provider',
        ),
        migrations.RemoveField(
            model_name='job',
            name='visibility',
        ),
        migrations.DeleteModel(
            name='DataProviderStatus',
        ),
    ]
