# Generated by Django 4.0.4 on 2022-08-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0028_auto_20220630_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataprovider',
            name='config',
        ),
        migrations.RenameField(
            model_name='dataprovider',
            old_name='config_json',
            new_name='config',
        ),
        migrations.AlterField(
            model_name='dataprovider',
            name='config',
            field=models.JSONField(default=dict, help_text="WMS, TMS, WMTS, and ArcGIS-Raster require a MapProxy YAML configuration\n                              with a Sources key of imagery and a Service Layer name of imagery; the validator also\n                              requires a layers section, but this isn't used.\n                              OSM Services also require a YAML configuration.", verbose_name='Configuration'),
        ),
    ]
