# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-18 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0028_auto_20180418_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataProviderStatus',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(blank=True, max_length=10)),
                ('status_type', models.CharField(blank=True, max_length=25)),
                ('message', models.CharField(blank=True, max_length=150)),
                ('last_check_time', models.DateTimeField(null=True)),
                ('related_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_provider_status', to='jobs.DataProvider')),
            ],
            options={
                'ordering': ['-last_check_time'],
                'verbose_name_plural': 'data provider statuses',
            },
        ),
        migrations.AddField(
            model_name='job',
            name='visibility',
            field=models.CharField(default='PRIVATE', max_length=10),
        ),
    ]
