# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-07 18:32

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models, connection, transaction


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0025_auto_20180213_2021'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', 'add_permissions_to_existing_jobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserJobActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.Job'))
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='last_export_run',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_export_run', to='tasks.ExportRun'),
        ),
    ]
