# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-14 03:59
from __future__ import unicode_literals

from django.db import migrations


def forwards_func(apps, schema_editor):
    Job = apps.get_model('jobs', 'Job')
    ExportRun = apps.get_model('tasks', 'ExportRun')

    # Get each job's latest export run and save a reference to it in the job.
    for job in Job.objects.all():
        export_run_query = ExportRun.objects.filter(job=job)
        if export_run_query.count() > 0:
            job.last_export_run = export_run_query.latest('created_at')
            job.save()


def reverse_func(apps, schema_editor):
    Job = apps.get_model('jobs', 'Job')
    for job in Job.objects.all():
        job.last_export_run = None
        job.save()


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0029_user_job_activity'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func)
    ]
