# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-06-19 13:15


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0029_auto_20180507_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='visibility',
            field=models.CharField(choices=[('PRIVATE', 'PRIVATE'), ('PUBLIC', 'PUBLIC'), ('SHARED', 'SHARED')], default='PRIVATE', max_length=10),
        ),
    ]
