# Generated by Django 2.0.8 on 2018-10-18 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0031_auto_20180920_1822'),
        ('jobs', 'add_last_run'),
    ]

    operations = [
    ]
