# Generated by Django 4.0.4 on 2022-09-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0033_userfavoriteproduct'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userfavoriteproduct',
            constraint=models.UniqueConstraint(fields=('user', 'provider'), name='unique_user_favorite_provider'),
        ),
    ]
