# Generated by Django 4.0.4 on 2022-10-20 17:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import eventkit_cloud.jobs.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0035_alter_dataprovider_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataprovider',
            name='config',
            field=eventkit_cloud.jobs.fields.ConfigJSONField(blank=True, default=dict, help_text="WMS, TMS, WMTS, and ArcGIS-Raster require a MapProxy YAML configuration\n                              with a Sources key of imagery and a Service Layer name of imagery; the validator also\n                              requires a layers section, but this isn't used.\n                              OSM Services also require a YAML configuration.", verbose_name='Configuration'),
        ),
        migrations.CreateModel(
            name='ProxyFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('identifier', models.CharField(max_length=40)),
                ('data_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.dataprovider', verbose_name='Data Provider')),
                ('export_format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.exportformat', verbose_name='Export Format')),
            ],
            options={
                'unique_together': {('data_provider', 'export_format')},
            },
        ),
    ]
