# Generated by Django 4.0.4 on 2022-10-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0036_alter_dataprovider_config_proxyformat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proxyformat',
            options={},
        ),
        migrations.RenameField(
            model_name='proxyformat',
            old_name='export_provider',
            new_name='data_provider',
        ),
        migrations.AlterField(
            model_name='proxyformat',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='proxyformat',
            unique_together={('data_provider', 'export_format')},
        ),
        migrations.AlterModelTable(
            name='proxyformat',
            table=None,
        ),
    ]
