# Generated by Django 2.2.3 on 2019-10-21 04:51

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', 'insert_default_supported_projections'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapImageSnapshot',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('filename', models.CharField(blank=True, editable=False, max_length=508)),
                ('size', models.FloatField(editable=False, null=True)),
                ('download_url', models.URLField(max_length=508, verbose_name='URL to export task result output.')),
            ],
            options={
                'db_table': 'MapImageSnapshot',
            },
        ),
        migrations.AddField(
            model_name='dataprovider',
            name='thumbnail',
            field=models.ForeignKey(blank=True, help_text="A thumbnail image generated to give a high level preview of what a provider's data looks like.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.MapImageSnapshot'),
        ),
    ]
