# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-07 18:32

from django.db import migrations, models, connection, transaction


def add_last_export_run(apps, schema_editor):

    # Get each job's latest export run and save a reference to it in the job.
    with transaction.atomic():
        Job = apps.get_model('jobs', 'Job')
        for job in Job.objects.all().prefetch_related('runs'):
            job.last_export_run = job.runs.last()
            job.save()


def remove_last_export_run(apps, schema_editor):
    Job = apps.get_model('jobs', 'Job')
    for job in Job.objects.all():
        job.last_export_run = None
        job.save()


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0029_auto_20180507_1832'),
        ('jobs', '0031_auto_20180920_1822'),
    ]

    operations = [
        migrations.RunPython(add_last_export_run, remove_last_export_run),
    ]
