package:
  name: libtiff
  version: 4.0.8

source:
  fn: tiff-4.0.8.zip
  url: http://download.osgeo.org/libtiff/tiff-4.0.8.zip

build:
  number: 0

about:
  home: http://download.osgeo.org/libtiff

# vim:set ts=8 sw=2 sts=2 tw=78 et: